#!/usr/bin/env python3
"""
Generates the Google Colab Notebook (.ipynb) for the production Movio automation pipeline.
Includes:
- Automated multi-language subtitle download (Arabic, English, French, Spanish)
- Fast MKV stream copy muxing (-c copy) with ffmpeg
- Aria2 directory pre-sanitization to prevent duplicate/exit status 13 errors
- Resilient DoodStream upload loop with fresh server re-allocation
- Strictly double-quoted WordPress iframe for Next.js regex compatibility
- DevSecOps secret hygiene (Colab userdata + empty form fields)
"""
import os
import json

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "name": "media_worker_pipeline.ipynb",
            "provenance": [],
            "toc_visible": True
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🎬 Movio Platform — Automated Cloud Ingestion Pipeline (Google Colab)\n",
                "**Production Cloud Pipeline for Headless WordPress (Pantheon) & Next.js**\n",
                "\n",
                "- **TMDB API**: High-resolution official metadata, poster, backdrop, rating, and synopsis.\n",
                "- **YTS API**: Best-quality torrent acquisition (1080p / 720p / magnet).\n",
                "- **Aria2c**: Multi-connection cloud download with pre-sanitization (resolves exit status 13).\n",
                "- **Multi-Language Subtitles**: Automated acquisition of Arabic, English, French, and Spanish subtitles via YIFY/IMDb.\n",
                "- **Fast MKV Muxing**: Zero-transcode stream copy (`-c copy`) via FFmpeg packaging video, audio, and subtitle streams.\n",
                "- **DoodStream API**: Resilient chunked streaming upload with auto-retry and fresh server allocation on connection drops.\n",
                "- **Pantheon REST API**: Headless WordPress post publishing with strictly double-quoted 16:9 responsive embed iframe and custom metadata."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title ⚙️ 1. Install Dependencies & Cloud Environment\n",
                "!apt-get update -qq\n",
                "!apt-get install -y -qq aria2 ffmpeg\n",
                "!pip install -q requests requests-toolbelt beautifulsoup4 python-dotenv tqdm\n",
                "!mkdir -p /content/download\n",
                "print(\"✅ Cloud Environment Ready: aria2c, FFmpeg, and Python dependencies installed.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 🔑 2. Cloud Configuration & Credentials (DevSecOps)\n",
                "# @markdown Configure your target Pantheon WordPress site and API keys.\n",
                "# @markdown Secrets can also be stored securely in Colab's encrypted Secrets sidebar.\n",
                "\n",
                "WP_SITE_URL = \"https://dev-movio-stream.pantheonsite.io\" # @param {type:\"string\"}\n",
                "WP_USERNAME = \"admin\" # @param {type:\"string\"}\n",
                "WP_APP_PASSWORD = \"\" # @param {type:\"string\"}\n",
                "TMDB_API_KEY = \"\" # @param {type:\"string\"}\n",
                "DOODSTREAM_API_KEY = \"\" # @param {type:\"string\"}\n",
                "\n",
                "# DevSecOps: Fallback to Colab Encrypted Secrets (key icon in sidebar)\n",
                "try:\n",
                "    from google.colab import userdata\n",
                "    WP_APP_PASSWORD = WP_APP_PASSWORD or userdata.get('WP_APP_PASSWORD')\n",
                "    TMDB_API_KEY = TMDB_API_KEY or userdata.get('TMDB_API_KEY')\n",
                "    DOODSTREAM_API_KEY = DOODSTREAM_API_KEY or userdata.get('DOODSTREAM_API_KEY')\n",
                "except Exception:\n",
                "    pass\n",
                "\n",
                "# DevSecOps: Fallback to Environment Variables\n",
                "import os\n",
                "WP_APP_PASSWORD = WP_APP_PASSWORD or os.getenv('WP_APP_PASSWORD', '')\n",
                "TMDB_API_KEY = TMDB_API_KEY or os.getenv('TMDB_API_KEY', '')\n",
                "DOODSTREAM_API_KEY = DOODSTREAM_API_KEY or os.getenv('DOODSTREAM_API_KEY', '')\n",
                "\n",
                "WP_SITE_URL = WP_SITE_URL.rstrip('/')\n",
                "print(f\"✅ Target WordPress CMS: {WP_SITE_URL}\")\n",
                "print(f\"✅ Credential Status: WP Auth: {'Configured' if WP_APP_PASSWORD else 'Missing'}, TMDB: {'Configured' if TMDB_API_KEY else 'Missing'}, DoodStream: {'Configured' if DOODSTREAM_API_KEY else 'Missing'}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 🌐 3. TMDB Metadata & YTS Torrent Engine\n",
                "import os, sys, re, time, json, shutil, zipfile, io, requests, subprocess\n",
                "from urllib.parse import quote\n",
                "from requests.auth import HTTPBasicAuth\n",
                "from bs4 import BeautifulSoup\n",
                "from requests_toolbelt import MultipartEncoder, MultipartEncoderMonitor\n",
                "\n",
                "HEADERS = {\n",
                "    \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36\",\n",
                "    \"Accept\": \"application/json, text/plain, */*\",\n",
                "}\n",
                "\n",
                "def fetch_tmdb_metadata(title, year=None, imdb_id=None):\n",
                "    print(f\"[TMDB] Querying metadata for '{title}' (Year: {year or 'Any'}, IMDb: {imdb_id or 'None'})...\")\n",
                "    item = None\n",
                "    if imdb_id and TMDB_API_KEY:\n",
                "        try:\n",
                "            res = requests.get(f\"https://api.themoviedb.org/3/find/{imdb_id}?api_key={TMDB_API_KEY}&external_source=imdb_id\", headers=HEADERS, timeout=15).json()\n",
                "            results = res.get(\"movie_results\", [])\n",
                "            if results: item = results[0]\n",
                "        except Exception as e: print(f\"[TMDB] IMDb lookup error: {e}\")\n",
                "\n",
                "    if not item and TMDB_API_KEY:\n",
                "        try:\n",
                "            url = f\"https://api.themoviedb.org/3/search/movie?api_key={TMDB_API_KEY}&query={quote(title)}\"\n",
                "            if year: url += f\"&year={year}\"\n",
                "            res = requests.get(url, headers=HEADERS, timeout=15).json()\n",
                "            results = res.get(\"results\", [])\n",
                "            if results: item = results[0]\n",
                "        except Exception as e: print(f\"[TMDB] Search error: {e}\")\n",
                "\n",
                "    genres = \"Action, Drama\"\n",
                "    rating = \"7.5\"\n",
                "    overview = \"No synopsis available.\"\n",
                "    poster_url = None\n",
                "    backdrop_url = None\n",
                "    final_title = title\n",
                "    final_year = year or \"2026\"\n",
                "    extracted_imdb = imdb_id\n",
                "\n",
                "    if item:\n",
                "        final_title = item.get(\"title\") or title\n",
                "        final_year = (item.get(\"release_date\") or \"\")[:4] or final_year\n",
                "        overview = item.get(\"overview\") or overview\n",
                "        rating = str(round(item.get(\"vote_average\", 7.5), 1))\n",
                "        if item.get(\"poster_path\"): poster_url = f\"https://image.tmdb.org/t/p/original{item['poster_path']}\"\n",
                "        if item.get(\"backdrop_path\"): backdrop_url = f\"https://image.tmdb.org/t/p/original{item['backdrop_path']}\"\n",
                "        if item.get(\"id\") and TMDB_API_KEY:\n",
                "            try:\n",
                "                d = requests.get(f\"https://api.themoviedb.org/3/movie/{item['id']}?api_key={TMDB_API_KEY}\", headers=HEADERS, timeout=15).json()\n",
                "                if \"genres\" in d: genres = \", \".join([g[\"name\"] for g in d[\"genres\"]])\n",
                "                extracted_imdb = d.get(\"imdb_id\") or extracted_imdb\n",
                "            except Exception: pass\n",
                "\n",
                "    if not poster_url:\n",
                "        poster_url = \"https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1000&q=85\"\n",
                "\n",
                "    meta = {\n",
                "        \"title\": final_title, \"year\": final_year, \"overview\": overview,\n",
                "        \"rating\": rating, \"genres\": genres, \"poster_url\": poster_url,\n",
                "        \"backdrop_url\": backdrop_url, \"imdb_id\": extracted_imdb\n",
                "    }\n",
                "    print(f\"[TMDB] ✅ Found: '{meta['title']}' ({meta['year']}) | ★ {meta['rating']} | {meta['genres']} | IMDb: {meta['imdb_id']}\")\n",
                "    return meta\n",
                "\n",
                "def fetch_yts_torrent(title, year=None, imdb_id=None, quality=\"1080p\"):\n",
                "    query = imdb_id if imdb_id else title\n",
                "    print(f\"[YTS] Searching torrent for '{query}'...\")\n",
                "    mirrors = [\"https://yts.mx\", \"https://yts.nz\", \"https://yts.lt\", \"https://yts.do\"]\n",
                "    data = None\n",
                "    for m in mirrors:\n",
                "        try:\n",
                "            r = requests.get(f\"{m}/api/v2/list_movies.json?query_term={quote(query)}&sort_by=download_count\", headers=HEADERS, timeout=15)\n",
                "            if r.status_code == 200:\n",
                "                rj = r.json()\n",
                "                if rj.get(\"status\") == \"ok\" and rj.get(\"data\", {}).get(\"movie_count\", 0) > 0:\n",
                "                    data = rj[\"data\"]\n",
                "                    print(f\"[YTS] Connected to {m} (Matches: {data['movie_count']})\")\n",
                "                    break\n",
                "        except Exception: continue\n",
                "\n",
                "    if not data or not data.get(\"movies\"):\n",
                "        raise RuntimeError(f\"No torrents found on YTS for '{query}'.\")\n",
                "\n",
                "    movies = data[\"movies\"]\n",
                "    target = movies[0]\n",
                "    if year:\n",
                "        for mv in movies:\n",
                "            if str(mv.get(\"year\")) == str(year):\n",
                "                target = mv; break\n",
                "\n",
                "    torrents = target.get(\"torrents\", [])\n",
                "    if not torrents:\n",
                "        raise RuntimeError(f\"No torrent streams available for '{target.get('title')}'.\")\n",
                "\n",
                "    sel = None\n",
                "    for q in [quality, \"1080p\", \"720p\", \"2160p\"]:\n",
                "        for t in torrents:\n",
                "            if t.get(\"quality\", \"\").lower() == q.lower():\n",
                "                sel = t; break\n",
                "        if sel: break\n",
                "    if not sel: sel = torrents[0]\n",
                "\n",
                "    h = sel.get(\"hash\")\n",
                "    q = sel.get(\"quality\", \"1080p\")\n",
                "    trackers = [\"udp://open.demonii.com:1337/announce\", \"udp://tracker.openbittorrent.com:80\", \"udp://tracker.opentrackr.org:1337/announce\"]\n",
                "    tr_args = \"&\".join([f\"tr={quote(t)}\" for t in trackers])\n",
                "    magnet = f\"magnet:?xt=urn:btih:{h}&dn={quote(target.get('title'))}&{tr_args}\"\n",
                "    print(f\"[YTS] ✅ Selected: {q} ({sel.get('size')}) Hash: {h[:10]}...\")\n",
                "    return {\"quality\": q, \"torrent_url\": sel.get(\"url\"), \"magnet_uri\": magnet, \"size\": sel.get(\"size\")}"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 📥 4. Aria2c Download & Sanitization Engine\n",
                "def sanitize_download_dir(download_dir=\"/content/download\"):\n",
                "    \"\"\"Clear incomplete chunks and control files to resolve aria2 exit status 13.\"\"\"\n",
                "    if not os.path.exists(download_dir):\n",
                "        os.makedirs(download_dir, exist_ok=True)\n",
                "        return\n",
                "    print(f\"[ARIA2] Sanitizing download directory: {download_dir}...\")\n",
                "    stale_exts = (\".aria2\", \".part\", \".tmp\", \".crdownload\")\n",
                "    for root, _, files in os.walk(download_dir):\n",
                "        for f in files:\n",
                "            if f.lower().endswith(stale_exts):\n",
                "                try:\n",
                "                    os.remove(os.path.join(root, f))\n",
                "                    print(f\"[ARIA2] Cleared stale file: {f}\")\n",
                "                except Exception: pass\n",
                "\n",
                "def download_with_aria2(source_uri, download_dir=\"/content/download\"):\n",
                "    \"\"\"High-speed cloud download using aria2c with overwrite and auto-renaming safety flags.\"\"\"\n",
                "    sanitize_download_dir(download_dir)\n",
                "    print(f\"[ARIA2] Starting multi-connection download into {download_dir}...\")\n",
                "    cmd = [\n",
                "        \"aria2c\", f\"--dir={download_dir}\", \"--max-connection-per-server=16\",\n",
                "        \"--split=16\", \"--min-split-size=1M\", \"--summary-interval=10\",\n",
                "        \"--seed-time=0\", \"--follow-torrent=mem\",\n",
                "        \"--allow-overwrite=true\", \"--auto-file-renaming=false\",\n",
                "        \"--conditional-get=true\", \"--file-allocation=none\",\n",
                "        source_uri\n",
                "    ]\n",
                "    proc = subprocess.run(cmd, capture_output=False)\n",
                "    if proc.returncode != 0:\n",
                "        raise RuntimeError(f\"aria2c download failed with exit code {proc.returncode}\")\n",
                "\n",
                "    videos = []\n",
                "    for root, _, files in os.walk(download_dir):\n",
                "        for f in files:\n",
                "            if f.lower().endswith((\".mp4\", \".mkv\", \".avi\", \".webm\")):\n",
                "                p = os.path.join(root, f)\n",
                "                videos.append((p, os.path.getsize(p)))\n",
                "\n",
                "    if not videos:\n",
                "        raise FileNotFoundError(f\"No video file downloaded in {download_dir}.\")\n",
                "    videos.sort(key=lambda x: x[1], reverse=True)\n",
                "    target_file = videos[0][0]\n",
                "    print(f\"[ARIA2] ✅ Downloaded: {os.path.basename(target_file)} ({videos[0][1]/(1024*1024):.1f} MB)\")\n",
                "    return target_file"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 💬 5. Multi-Language Subtitles & Fast MKV Muxing\n",
                "def download_subtitles_for_imdb(imdb_id, output_dir=\"/content/download\", target_languages=None):\n",
                "    \"\"\"Fetch matching .srt subtitles (Arabic, English, French, Spanish) via YIFY/IMDb.\"\"\"\n",
                "    if not imdb_id:\n",
                "        print(\"[SUBS] No IMDb ID available; skipping subtitle download.\")\n",
                "        return {}\n",
                "    if not target_languages:\n",
                "        target_languages = [\"arabic\", \"english\", \"french\", \"spanish\"]\n",
                "\n",
                "    subs_dir = os.path.join(output_dir, \"subtitles\")\n",
                "    os.makedirs(subs_dir, exist_ok=True)\n",
                "    lang_map = {\"arabic\": \"ara\", \"english\": \"eng\", \"french\": \"fre\", \"spanish\": \"spa\"}\n",
                "    print(f\"[SUBS] Fetching subtitles for IMDb ID '{imdb_id}' in {target_languages}...\")\n",
                "    subs_found = {}\n",
                "\n",
                "    # 1. Try JSON endpoint\n",
                "    try:\n",
                "        r = requests.get(f\"https://api.yifysubtitles.ch/subs/{imdb_id}\", headers=HEADERS, timeout=6)\n",
                "        if r.status_code == 200:\n",
                "            d = r.json().get(\"subs\", {}).get(imdb_id, {})\n",
                "            for lang in target_languages:\n",
                "                if lang in d and d[lang]:\n",
                "                    sub_u = d[lang][0].get(\"url\", \"\")\n",
                "                    if sub_u: subs_found[lang] = sub_u\n",
                "    except Exception: pass\n",
                "\n",
                "    # 2. Resilient fallback to HTML mirrors\n",
                "    if len(subs_found) < len(target_languages):\n",
                "        for mirror in [f\"https://yifysubtitles.ch/movie-imdb/{imdb_id}\", f\"https://yts-subs.com/movie-imdb/{imdb_id}\", f\"https://yifysubtitles.org/movie-imdb/{imdb_id}\"]:\n",
                "            try:\n",
                "                r = requests.get(mirror, headers=HEADERS, timeout=10)\n",
                "                if r.status_code == 200:\n",
                "                    soup = BeautifulSoup(r.text, \"html.parser\")\n",
                "                    for tr in soup.find_all(\"tr\"):\n",
                "                        tag = tr.find(class_=\"sub-lang\")\n",
                "                        if not tag: continue\n",
                "                        name = tag.text.strip().lower()\n",
                "                        if name in target_languages and name not in subs_found:\n",
                "                            a = tr.find(\"a\", href=True)\n",
                "                            if a and \"/subtitles/\" in a[\"href\"]: subs_found[name] = a[\"href\"]\n",
                "                    if subs_found: break\n",
                "            except Exception: continue\n",
                "\n",
                "    downloaded = {}\n",
                "    for lang, link in subs_found.items():\n",
                "        try:\n",
                "            slug = link.rstrip(\"/\").split(\"/\")[-1]\n",
                "            zip_u = f\"https://yifysubtitles.ch/subtitle/{slug}.zip\"\n",
                "            h = {\"User-Agent\": HEADERS[\"User-Agent\"], \"Referer\": f\"https://yifysubtitles.ch/subtitles/{slug}\"}\n",
                "            zr = requests.get(zip_u, headers=h, timeout=15)\n",
                "            if zr.status_code == 200:\n",
                "                with zipfile.ZipFile(io.BytesIO(zr.content)) as z:\n",
                "                    for fname in z.namelist():\n",
                "                        if fname.lower().endswith(\".srt\"):\n",
                "                            code = lang_map.get(lang, lang[:3])\n",
                "                            out_p = os.path.join(subs_dir, f\"{imdb_id}_{code}.srt\")\n",
                "                            with open(out_p, \"wb\") as sf: sf.write(z.read(fname))\n",
                "                            downloaded[code] = out_p\n",
                "                            print(f\"[SUBS] ✅ Downloaded {lang} ({code}) -> {os.path.basename(out_p)}\")\n",
                "                            break\n",
                "        except Exception as e: print(f\"[SUBS] Error downloading {lang}: {e}\")\n",
                "    return downloaded\n",
                "\n",
                "def embed_subtitles_to_mkv(video_path, subtitles_dict):\n",
                "    \"\"\"Mux subtitles into an MKV container using fast stream copy (-c copy).\"\"\"\n",
                "    if not subtitles_dict:\n",
                "        print(\"[MUX] No subtitles provided; continuing with original video.\")\n",
                "        return video_path\n",
                "    if not shutil.which(\"ffmpeg\"):\n",
                "        print(\"[MUX] ffmpeg not found; skipping MKV muxing.\")\n",
                "        return video_path\n",
                "\n",
                "    base, _ = os.path.splitext(video_path)\n",
                "    out_mkv = f\"{base}_subbed.mkv\"\n",
                "    if os.path.abspath(out_mkv) == os.path.abspath(video_path):\n",
                "        out_mkv = f\"{base}_muxed.mkv\"\n",
                "\n",
                "    print(f\"[MUX] Packaging {len(subtitles_dict)} subtitle tracks into MKV: {os.path.basename(out_mkv)}...\")\n",
                "    cmd = [\"ffmpeg\", \"-y\", \"-i\", video_path]\n",
                "    sub_keys = list(subtitles_dict.keys())\n",
                "    for l in sub_keys: cmd.extend([\"-i\", subtitles_dict[l]])\n",
                "    cmd.extend([\"-map\", \"0:v\", \"-map\", \"0:a?\"])\n",
                "\n",
                "    lang_titles = {\"ara\": \"Arabic\", \"eng\": \"English\", \"fre\": \"French\", \"spa\": \"Spanish\"}\n",
                "    for idx, l in enumerate(sub_keys):\n",
                "        cmd.extend([\"-map\", str(idx + 1)])\n",
                "        t = lang_titles.get(l, l.upper())\n",
                "        cmd.extend([f\"-metadata:s:s:{idx}\", f\"language={l}\", f\"-metadata:s:s:{idx}\", f\"title={t}\", f\"-metadata:s:s:{idx}\", f\"handler_name={t}\"])\n",
                "\n",
                "    cmd.extend([\"-c\", \"copy\", out_mkv])\n",
                "    proc = subprocess.run(cmd, capture_output=True, text=True)\n",
                "    if proc.returncode != 0:\n",
                "        print(f\"[MUX] Warning: ffmpeg muxing notice: {proc.stderr[-200:]}. Using raw video.\")\n",
                "        return video_path\n",
                "\n",
                "    if os.path.exists(out_mkv) and os.path.getsize(out_mkv) > 0:\n",
                "        print(f\"[MUX] ✅ Muxing complete! MKV Container: {os.path.basename(out_mkv)} ({os.path.getsize(out_mkv)/(1024*1024):.1f} MB)\")\n",
                "        if os.path.abspath(video_path) != os.path.abspath(out_mkv):\n",
                "            try: os.remove(video_path)\n",
                "            except Exception: pass\n",
                "        return out_mkv\n",
                "    return video_path"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title ☁️ 6. Resilient DoodStream Upload Engine\n",
                "def upload_to_doodstream(video_path, max_retries=3):\n",
                "    \"\"\"Chunked streaming upload to DoodStream API with retry loop and new server allocation on disconnect.\"\"\"\n",
                "    if not DOODSTREAM_API_KEY:\n",
                "        raise ValueError(\"DOODSTREAM_API_KEY is not configured. Please supply an API key in Cell 2.\")\n",
                "\n",
                "    fname = os.path.basename(video_path)\n",
                "    size_mb = os.path.getsize(video_path) / (1024 * 1024)\n",
                "    last_err = None\n",
                "\n",
                "    for attempt in range(1, max_retries + 1):\n",
                "        try:\n",
                "            print(f\"[DOOD] Requesting fresh upload server (Attempt {attempt}/{max_retries})...\")\n",
                "            srv_resp = requests.get(\"https://doodapi.com/api/upload/server\", params={\"key\": DOODSTREAM_API_KEY}, timeout=30).json()\n",
                "            if srv_resp.get(\"status\") != 200 or not srv_resp.get(\"result\"):\n",
                "                raise RuntimeError(f\"Failed to allocate upload server: {srv_resp}\")\n",
                "\n",
                "            upload_url = srv_resp[\"result\"]\n",
                "            print(f\"[DOOD] Uploading '{fname}' ({size_mb:.1f} MB) via {upload_url[:45]}...\")\n",
                "\n",
                "            with open(video_path, 'rb') as f:\n",
                "                encoder = MultipartEncoder(fields={'api_key': DOODSTREAM_API_KEY, 'file': (fname, f, 'video/mp4')})\n",
                "                last_pct = [-1]\n",
                "                def progress(m):\n",
                "                    pct = int((m.bytes_read / m.len) * 100)\n",
                "                    if pct % 10 == 0 and pct != last_pct[0]:\n",
                "                        last_pct[0] = pct\n",
                "                        print(f\"  [Upload Progress] {pct}% ({m.bytes_read/(1024*1024):.1f} MB / {m.len/(1024*1024):.1f} MB)\", flush=True)\n",
                "                monitor = MultipartEncoderMonitor(encoder, progress)\n",
                "                resp = requests.post(upload_url, data=monitor, headers={'Content-Type': monitor.content_type}, timeout=7200).json()\n",
                "\n",
                "            if resp.get(\"status\") != 200:\n",
                "                raise RuntimeError(f\"DoodStream rejected upload: {resp}\")\n",
                "\n",
                "            res = resp[\"result\"]\n",
                "            code = res[0][\"filecode\"] if isinstance(res, list) else res[\"filecode\"]\n",
                "            embed = f\"https://doodstream.com/e/{code}\"\n",
                "            print(f\"[DOOD] ✅ Upload successful! Embed: {embed}\")\n",
                "            return embed\n",
                "        except Exception as e:\n",
                "            last_err = e\n",
                "            print(f\"[DOOD] Upload attempt {attempt} notice: {e.__class__.__name__}: {e}\")\n",
                "            if attempt < max_retries:\n",
                "                wait_sec = attempt * 7\n",
                "                print(f\"[DOOD] Waiting {wait_sec}s before requesting a fresh upload server...\")\n",
                "                time.sleep(wait_sec)\n",
                "\n",
                "    raise RuntimeError(f\"DoodStream upload failed after {max_retries} attempts. Last error: {last_err}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 📝 7. Headless WordPress Publisher (Strict Double Quotes)\n",
                "def upload_poster_to_pantheon(image_url, slug):\n",
                "    if not image_url: return None\n",
                "    print(f\"[WP] Downloading TMDB poster: {image_url[:80]}...\")\n",
                "    img_data = requests.get(image_url, headers=HEADERS, timeout=30).content\n",
                "    h = {\n",
                "        \"Content-Disposition\": f'attachment; filename=\"{slug[:25]}_{int(time.time())}.jpg\"',\n",
                "        \"Content-Type\": \"image/jpeg\",\n",
                "        \"User-Agent\": HEADERS[\"User-Agent\"]\n",
                "    }\n",
                "    auth = HTTPBasicAuth(WP_USERNAME, WP_APP_PASSWORD) if WP_APP_PASSWORD else None\n",
                "    res = requests.post(f\"{WP_SITE_URL}/wp-json/wp/v2/media\", headers=h, data=img_data, auth=auth, timeout=40)\n",
                "    if res.status_code in (200, 201):\n",
                "        mid = res.json()[\"id\"]\n",
                "        print(f\"[WP] ✅ Poster attached to Pantheon Media Library (ID: {mid})\")\n",
                "        return mid\n",
                "    print(f\"[WP] Poster upload notice ({res.status_code}): {res.text[:100]}\")\n",
                "    return None\n",
                "\n",
                "def publish_movie_to_pantheon(meta, embed_url, quality=\"1080p\"):\n",
                "    \"\"\"Publish post to Pantheon WordPress with strict double quotes on iframe for Next.js regex parser.\"\"\"\n",
                "    slug = re.sub(r'[^a-zA-Z0-9]+', '-', meta['title'].lower()).strip('-')\n",
                "    media_id = upload_poster_to_pantheon(meta.get(\"poster_url\"), slug)\n",
                "    title = f\"{meta['title']} ({meta['year']})\"\n",
                "    print(f\"[WP] Publishing '{title}' to Pantheon WordPress...\")\n",
                "\n",
                "    # STRICT double quotes on iframe attributes ensure Next.js player matches cleanly\n",
                "    content = f\"\"\"<div class=\"video-container\" style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; border-radius: 12px; margin-bottom: 1.5rem;\">\n",
                "    <iframe src=\"{embed_url}\" style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;\" allowfullscreen=\"true\" scrolling=\"no\" frameborder=\"0\"></iframe>\n",
                "</div>\n",
                "<div class=\"movie-meta-summary\">\n",
                "    <p><strong>Rating:</strong> {meta.get('rating', '8.0')} / 10</p>\n",
                "    <p><strong>Release Year:</strong> {meta.get('year', '2026')}</p>\n",
                "    <p><strong>Genres:</strong> {meta.get('genres', 'Movies')}</p>\n",
                "    <p><strong>Quality:</strong> {quality} Full HD</p>\n",
                "    <hr>\n",
                "    <p>{meta.get('overview', '')}</p>\n",
                "</div>\"\"\"\n",
                "\n",
                "    payload = {\n",
                "        \"title\": title,\n",
                "        \"content\": content,\n",
                "        \"status\": \"publish\",\n",
                "        \"meta\": {\n",
                "            \"embed_url\": embed_url,\n",
                "            \"dood_embed\": embed_url,\n",
                "            \"video_year\": str(meta.get(\"year\", \"2026\")),\n",
                "            \"imdb_rating\": str(meta.get(\"rating\", \"8.0\")),\n",
                "            \"quality\": quality,\n",
                "            \"backdrop_url\": meta.get(\"backdrop_url\") or \"\",\n",
                "            \"genres\": meta.get(\"genres\", \"\")\n",
                "        }\n",
                "    }\n",
                "    if media_id: payload[\"featured_media\"] = media_id\n",
                "    auth = HTTPBasicAuth(WP_USERNAME, WP_APP_PASSWORD) if WP_APP_PASSWORD else None\n",
                "    res = requests.post(f\"{WP_SITE_URL}/wp-json/wp/v2/posts\", json=payload, headers=HEADERS, auth=auth, timeout=30)\n",
                "    if res.status_code in (200, 201):\n",
                "        data = res.json()\n",
                "        print(f\"🎉 SUCCESS: Movie published to Pantheon WordPress!\")\n",
                "        print(f\"Post ID:   {data.get('id')}\")\n",
                "        print(f\"Post Slug: {data.get('slug')}\")\n",
                "        print(f\"Live Post: {data.get('link')}\")\n",
                "        return data\n",
                "    raise RuntimeError(f\"WP publish failed ({res.status_code}): {res.text[:250]}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 🚀 8. Master Pipeline Execution\n",
                "# @markdown Specify Movie Name and Year (or IMDb ID):\n",
                "\n",
                "MOVIE_TITLE = \"The Beekeeper\" # @param {type:\"string\"}\n",
                "RELEASE_YEAR = \"2024\" # @param {type:\"string\"}\n",
                "IMDB_ID = \"\" # @param {type:\"string\"}\n",
                "PREFERRED_QUALITY = \"1080p\" # @param [\"1080p\", \"720p\", \"2160p\"]\n",
                "\n",
                "def run_pipeline(title, year=None, imdb=None, quality=\"1080p\"):\n",
                "    print(\"=\" * 75)\n",
                "    print(\"  MOVIO CLOUD AUTOMATION PIPELINE (TMDB + YTS + ARIA2C + SUBS + PANTHEON)\")\n",
                "    print(\"=\" * 75)\n",
                "    # 1. TMDB Metadata\n",
                "    meta = fetch_tmdb_metadata(title.strip(), year.strip() if year else None, imdb.strip() if imdb else None)\n",
                "\n",
                "    # 2. YTS Torrent\n",
                "    target_imdb = meta.get(\"imdb_id\") or (imdb.strip() if imdb else None)\n",
                "    torrent = fetch_yts_torrent(meta[\"title\"], meta[\"year\"], target_imdb, quality)\n",
                "\n",
                "    # 3. High-Speed Aria2c Download (Sanitized)\n",
                "    raw_video = download_with_aria2(torrent[\"torrent_url\"] or torrent[\"magnet_uri\"])\n",
                "\n",
                "    # 4. Multi-Language Subtitles & Fast MKV Muxing\n",
                "    subs = download_subtitles_for_imdb(target_imdb, \"/content/download\")\n",
                "    final_video = embed_subtitles_to_mkv(raw_video, subs)\n",
                "\n",
                "    # 5. Resilient DoodStream Upload\n",
                "    embed_url = upload_to_doodstream(final_video)\n",
                "\n",
                "    # 6. Publish to Pantheon WordPress (Strict Double Quotes)\n",
                "    post_data = publish_movie_to_pantheon(meta, embed_url, torrent[\"quality\"])\n",
                "\n",
                "    # 7. Clean up temporary files to preserve Colab disk space\n",
                "    for path in set([final_video, raw_video] + list(subs.values())):\n",
                "        if path and os.path.exists(path):\n",
                "            try:\n",
                "                os.remove(path)\n",
                "                print(f\"[CLEANUP] Deleted temporary file: {os.path.basename(path)}\")\n",
                "            except Exception: pass\n",
                "\n",
                "    print(\"\\n\" + \"=\" * 75)\n",
                "    print(\"  PIPELINE COMPLETED SUCCESSFULLY!\")\n",
                "    print(f\"  Movie:     {meta['title']} ({meta['year']})\")\n",
                "    print(f\"  Rating:    ★ {meta['rating']}\")\n",
                "    print(f\"  Subtitles: {list(subs.keys()) if subs else 'None'}\")\n",
                "    print(f\"  Embed:     {embed_url}\")\n",
                "    print(f\"  Live Post: {post_data.get('link')}\")\n",
                "    print(f\"  Next.js:   https://your-vercel-domain.vercel.app/movie/{post_data.get('slug')}\")\n",
                "    print(\"=\" * 75)\n",
                "    return post_data\n",
                "\n",
                "# Execute pipeline with configured inputs\n",
                "post_result = run_pipeline(MOVIE_TITLE, RELEASE_YEAR, IMDB_ID, PREFERRED_QUALITY)"
            ]
        }
    ]
}

notebook_path = os.path.abspath("notebooks/media_worker_pipeline.ipynb")
os.makedirs(os.path.dirname(notebook_path), exist_ok=True)
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Generated Production Colab Notebook at: {notebook_path}")
