#!/usr/bin/env python3
"""
Generates the Google Colab Notebook (.ipynb) for the production Movio automation pipeline.
"""
import os
import json

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "name": "media_worker_pipeline.ipynb",
            "provenance": [],
            "toc_visible": True
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🎬 Movio Platform — Automated Cloud Ingestion Pipeline (Google Colab)\n",
                "**Production Pipeline for Headless WordPress (Pantheon) & Next.js**\n",
                "\n",
                "- **TMDB API**: Verified high-resolution poster (original), backdrop, rating, and overview.\n",
                "- **YTS API**: High-quality torrent acquisition (1080p / 720p / magnet).\n",
                "- **Aria2c**: Multi-connection cloud download directly into `/content/download` at 1 Gbps.\n",
                "- **DoodStream API**: Chunked video upload with progress monitoring.\n",
                "- **Pantheon REST API**: Headless WordPress post publishing with responsive 16:9 iframe player and custom metadata.\n"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title ⚙️ 1. Install Dependencies & Cloud Environment\n",
                "!apt-get update -qq\n",
                "!apt-get install -y -qq aria2 ffmpeg\n",
                "!pip install -q requests requests-toolbelt beautifulsoup4 python-dotenv tqdm\n",
                "!mkdir -p /content/download\n",
                "print(\"✅ Cloud Environment Ready: aria2c, FFmpeg, and Python libraries installed.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 🔑 2. Cloud Configuration & Credentials\n",
                "# @markdown Configure your target Pantheon WordPress site and API keys:\n",
                "\n",
                "WP_SITE_URL = \"https://dev-movio-stream.pantheonsite.io\" # @param {type:\"string\"}\n",
                "WP_USERNAME = \"admin\" # @param {type:\"string\"}\n",
                "WP_APP_PASSWORD = \"\" # @param {type:\"string\"}\n",
                "TMDB_API_KEY = \"b35f606354897f26c58be0343a41e97a\" # @param {type:\"string\"}\n",
                "DOODSTREAM_API_KEY = \"578084xvwvf2mt7is4dgrb\" # @param {type:\"string\"}\n",
                "\n",
                "WP_SITE_URL = WP_SITE_URL.rstrip('/')\n",
                "print(f\"✅ Target WordPress CMS: {WP_SITE_URL}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 🛠️ 3. Pipeline Core Functions\n",
                "import os, sys, re, time, json, requests, subprocess\n",
                "from urllib.parse import quote\n",
                "from requests.auth import HTTPBasicAuth\n",
                "from requests_toolbelt import MultipartEncoder, MultipartEncoderMonitor\n",
                "\n",
                "HEADERS = {\n",
                "    \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36\",\n",
                "    \"Accept\": \"application/json, text/plain, */*\",\n",
                "}\n",
                "\n",
                "def fetch_tmdb_metadata(title, year=None, imdb_id=None):\n",
                "    print(f\"[TMDB] Querying TMDB for '{title}' (Year: {year or 'Any'}, IMDb: {imdb_id or 'None'})...\")\n",
                "    movie_item = None\n",
                "    if imdb_id and TMDB_API_KEY:\n",
                "        try:\n",
                "            res = requests.get(f\"https://api.themoviedb.org/3/find/{imdb_id}?api_key={TMDB_API_KEY}&external_source=imdb_id\", headers=HEADERS, timeout=15).json()\n",
                "            if res.get(\"movie_results\"):\n",
                "                movie_item = res[\"movie_results\"][0]\n",
                "        except Exception as e:\n",
                "            print(f\"[TMDB] IMDb error: {e}\")\n",
                "    if not movie_item and TMDB_API_KEY:\n",
                "        try:\n",
                "            url = f\"https://api.themoviedb.org/3/search/movie?api_key={TMDB_API_KEY}&query={quote(title)}\"\n",
                "            if year: url += f\"&year={year}\"\n",
                "            res = requests.get(url, headers=HEADERS, timeout=15).json()\n",
                "            if res.get(\"results\"):\n",
                "                movie_item = res[\"results\"][0]\n",
                "        except Exception as e:\n",
                "            print(f\"[TMDB] Search error: {e}\")\n",
                "\n",
                "    final_title = movie_item.get(\"title\") if movie_item else title\n",
                "    final_year = (movie_item.get(\"release_date\") or \"\")[:4] if movie_item else (year or \"2026\")\n",
                "    overview = movie_item.get(\"overview\") if movie_item else \"No overview available.\"\n",
                "    rating = str(round(movie_item.get(\"vote_average\", 7.5), 1)) if movie_item else \"7.5\"\n",
                "    poster_url = f\"https://image.tmdb.org/t/p/original{movie_item.get('poster_path')}\" if (movie_item and movie_item.get(\"poster_path\")) else \"https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1000&q=85\"\n",
                "    backdrop_url = f\"https://image.tmdb.org/t/p/original{movie_item.get('backdrop_path')}\" if (movie_item and movie_item.get(\"backdrop_path\")) else None\n",
                "    genres = \"Action, Drama\"\n",
                "    if movie_item and movie_item.get(\"id\") and TMDB_API_KEY:\n",
                "        try:\n",
                "            d = requests.get(f\"https://api.themoviedb.org/3/movie/{movie_item['id']}?api_key={TMDB_API_KEY}\", headers=HEADERS, timeout=15).json()\n",
                "            if \"genres\" in d: genres = \", \".join([g[\"name\"] for g in d[\"genres\"]])\n",
                "        except Exception:\n",
                "            pass\n",
                "    return {\"title\": final_title, \"year\": final_year, \"overview\": overview, \"rating\": rating, \"poster_url\": poster_url, \"backdrop_url\": backdrop_url, \"genres\": genres, \"imdb_id\": imdb_id}\n",
                "\n",
                "def fetch_yts_torrent(title, year=None, imdb_id=None, pref_quality=\"1080p\"):\n",
                "    term = imdb_id if imdb_id else title\n",
                "    print(f\"[YTS] Searching for torrent: '{term}'...\")\n",
                "    mirrors = [\"https://yts.mx\", \"https://yts.nz\", \"https://yts.lt\", \"https://yts.do\"]\n",
                "    data = None\n",
                "    for m in mirrors:\n",
                "        try:\n",
                "            r = requests.get(f\"{m}/api/v2/list_movies.json?query_term={quote(term)}&sort_by=download_count\", headers=HEADERS, timeout=15)\n",
                "            if r.status_code == 200:\n",
                "                j = r.json()\n",
                "                if j.get(\"status\") == \"ok\" and j.get(\"data\", {}).get(\"movie_count\", 0) > 0:\n",
                "                    data = j[\"data\"]\n",
                "                    break\n",
                "        except Exception:\n",
                "            continue\n",
                "    if not data or not data.get(\"movies\"):\n",
                "        raise RuntimeError(f\"No torrents found on YTS for '{term}'.\")\n",
                "    movies = data[\"movies\"]\n",
                "    target = movies[0]\n",
                "    if year:\n",
                "        for mv in movies:\n",
                "            if str(mv.get(\"year\")) == str(year):\n",
                "                target = mv; break\n",
                "    torrents = target.get(\"torrents\", [])\n",
                "    if not torrents:\n",
                "        raise RuntimeError(f\"No torrent streams available for '{target.get('title')}'.\")\n",
                "    sel = None\n",
                "    for q in [pref_quality, \"1080p\", \"720p\", \"2160p\"]:\n",
                "        for t in torrents:\n",
                "            if t.get(\"quality\", \"\").lower() == q.lower():\n",
                "                sel = t; break\n",
                "        if sel: break\n",
                "    if not sel: sel = torrents[0]\n",
                "    thash = sel.get(\"hash\")\n",
                "    trackers = [\"udp://open.demonii.com:1337/announce\", \"udp://tracker.openbittorrent.com:80\", \"udp://tracker.coppersurfer.tk:6969\", \"udp://glotorrents.pw:6969/announce\", \"udp://tracker.opentrackr.org:1337/announce\"]\n",
                "    t_args = \"&\".join([f\"tr={quote(tr)}\" for tr in trackers])\n",
                "    magnet = f\"magnet:?xt=urn:btih:{thash}&dn={quote(target.get('title'))}&{t_args}\"\n",
                "    print(f\"[YTS] Found: {target.get('title')} | Quality: {sel.get('quality')} | Size: {sel.get('size')}\")\n",
                "    return {\"quality\": sel.get(\"quality\", \"1080p\"), \"torrent_url\": sel.get(\"url\"), \"magnet_uri\": magnet}\n",
                "\n",
                "def download_with_aria2(source, dest_dir=\"/content/download\"):\n",
                "    os.makedirs(dest_dir, exist_ok=True)\n",
                "    print(f\"[ARIA2] Starting high-speed download into {dest_dir}...\")\n",
                "    cmd = [\"aria2c\", f\"--dir={dest_dir}\", \"-s16\", \"-x16\", \"-k1M\", \"--seed-time=0\", \"--summary-interval=10\", \"--follow-torrent=mem\", source]\n",
                "    subprocess.run(cmd, check=True)\n",
                "    videos = []\n",
                "    for root, _, files in os.walk(dest_dir):\n",
                "        for f in files:\n",
                "            if f.lower().endswith((\".mp4\", \".mkv\", \".avi\", \".webm\")):\n",
                "                fp = os.path.join(root, f)\n",
                "                videos.append((fp, os.path.getsize(fp)))\n",
                "    if not videos:\n",
                "        raise FileNotFoundError(\"No video file found in download directory.\")\n",
                "    videos.sort(key=lambda x: x[1], reverse=True)\n",
                "    video_path = videos[0][0]\n",
                "    print(f\"[ARIA2] Downloaded: {os.path.basename(video_path)} ({videos[0][1]/(1024*1024):.1f} MB)\")\n",
                "    return video_path\n",
                "\n",
                "def upload_to_doodstream(video_path):\n",
                "    print(\"[DOOD] Requesting DoodStream upload server...\")\n",
                "    srv = requests.get(\"https://doodapi.com/api/upload/server\", params={\"key\": DOODSTREAM_API_KEY}, timeout=30).json()\n",
                "    upload_url = srv[\"result\"]\n",
                "    fname = os.path.basename(video_path)\n",
                "    print(f\"[DOOD] Uploading '{fname}' ({os.path.getsize(video_path)/(1024*1024):.1f} MB)...\")\n",
                "    with open(video_path, 'rb') as f:\n",
                "        encoder = MultipartEncoder(fields={'api_key': DOODSTREAM_API_KEY, 'file': (fname, f, 'video/mp4')})\n",
                "        last = [-1]\n",
                "        def progress(m):\n",
                "            pct = int((m.bytes_read / m.len) * 100)\n",
                "            if pct % 10 == 0 and pct != last[0]:\n",
                "                last[0] = pct\n",
                "                print(f\"  [Upload Progress] {pct}% ({m.bytes_read/(1024*1024):.1f} MB / {m.len/(1024*1024):.1f} MB)\", flush=True)\n",
                "        monitor = MultipartEncoderMonitor(encoder, progress)\n",
                "        resp = requests.post(upload_url, data=monitor, headers={'Content-Type': monitor.content_type}, timeout=7200).json()\n",
                "    code = resp[\"result\"][0][\"filecode\"] if isinstance(resp[\"result\"], list) else resp[\"result\"][\"filecode\"]\n",
                "    embed = f\"https://doodstream.com/e/{code}\"\n",
                "    print(f\"[DOOD] ✅ Upload complete! Embed URL: {embed}\")\n",
                "    return embed\n",
                "\n",
                "def upload_poster_to_pantheon(image_url, slug):\n",
                "    if not image_url: return None\n",
                "    print(f\"[WP] Downloading TMDB poster: {image_url[:80]}...\")\n",
                "    img_data = requests.get(image_url, headers=HEADERS, timeout=30).content\n",
                "    h = {\n",
                "        \"Content-Disposition\": f'attachment; filename=\"{slug[:25]}_{int(time.time())}.jpg\"',\n",
                "        \"Content-Type\": \"image/jpeg\",\n",
                "        \"User-Agent\": HEADERS[\"User-Agent\"]\n",
                "    }\n",
                "    auth = HTTPBasicAuth(WP_USERNAME, WP_APP_PASSWORD) if WP_APP_PASSWORD else None\n",
                "    res = requests.post(f\"{WP_SITE_URL}/wp-json/wp/v2/media\", headers=h, data=img_data, auth=auth, timeout=40)\n",
                "    if res.status_code in (200, 201):\n",
                "        mid = res.json()[\"id\"]\n",
                "        print(f\"[WP] ✅ Poster uploaded to Pantheon (Media ID: {mid})\")\n",
                "        return mid\n",
                "    print(f\"[WP] Poster notice ({res.status_code}): {res.text[:100]}\")\n",
                "    return None\n",
                "\n",
                "def publish_movie_to_pantheon(meta, embed_url, quality=\"1080p\"):\n",
                "    slug = re.sub(r'[^a-zA-Z0-9]+', '-', meta['title'].lower()).strip('-')\n",
                "    media_id = upload_poster_to_pantheon(meta.get(\"poster_url\"), slug)\n",
                "    title = f\"{meta['title']} ({meta['year']})\"\n",
                "    print(f\"[WP] Publishing '{title}' to Pantheon...\")\n",
                "    content = f\"\"\"<div class='video-container' style='position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; border-radius: 12px; margin-bottom: 1.5rem;'>\n",
                "  <iframe src='{embed_url}' style='position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;' allowfullscreen scrolling='no'></iframe>\n",
                "</div>\n",
                "<div class='movie-meta-summary'>\n",
                "  <p><strong>Rating:</strong> {meta.get('rating', '8.0')} / 10</p>\n",
                "  <p><strong>Release Year:</strong> {meta.get('year', '2026')}</p>\n",
                "  <p><strong>Genres:</strong> {meta.get('genres', 'Movies')}</p>\n",
                "  <p><strong>Quality:</strong> {quality} Full HD</p>\n",
                "  <hr>\n",
                "  <p>{meta.get('overview', '')}</p>\n",
                "</div>\"\"\"\n",
                "    payload = {\n",
                "        \"title\": title, \"content\": content, \"status\": \"publish\",\n",
                "        \"meta\": {\"embed_url\": embed_url, \"video_year\": str(meta.get(\"year\", \"2026\")), \"imdb_rating\": str(meta.get(\"rating\", \"8.0\")), \"quality\": quality, \"backdrop_url\": meta.get(\"backdrop_url\") or \"\", \"genres\": meta.get(\"genres\", \"\")}\n",
                "    }\n",
                "    if media_id: payload[\"featured_media\"] = media_id\n",
                "    auth = HTTPBasicAuth(WP_USERNAME, WP_APP_PASSWORD) if WP_APP_PASSWORD else None\n",
                "    res = requests.post(f\"{WP_SITE_URL}/wp-json/wp/v2/posts\", json=payload, headers=HEADERS, auth=auth, timeout=30)\n",
                "    if res.status_code in (200, 201):\n",
                "        data = res.json()\n",
                "        print(f\"🎉 SUCCESS: Movie published to Pantheon WordPress!\")\n",
                "        print(f\"WordPress Post URL: {data.get('link')}\")\n",
                "        return data\n",
                "    raise RuntimeError(f\"WP publish failed ({res.status_code}): {res.text[:250]}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 🚀 4. Run Movie Ingestion Pipeline\n",
                "# @markdown Specify Movie Name and Year (or IMDb ID):\n",
                "\n",
                "MOVIE_TITLE = \"The Beekeeper\" # @param {type:\"string\"}\n",
                "RELEASE_YEAR = \"2024\" # @param {type:\"string\"}\n",
                "IMDB_ID = \"\" # @param {type:\"string\"}\n",
                "PREFERRED_QUALITY = \"1080p\" # @param [\"1080p\", \"720p\", \"2160p\"]\n",
                "\n",
                "# 1. TMDB Metadata & High-Res Poster\n",
                "meta = fetch_tmdb_metadata(MOVIE_TITLE.strip(), RELEASE_YEAR.strip() or None, IMDB_ID.strip() or None)\n",
                "\n",
                "# 2. YTS Torrent\n",
                "torrent = fetch_yts_torrent(meta[\"title\"], meta[\"year\"], meta.get(\"imdb_id\"), PREFERRED_QUALITY)\n",
                "\n",
                "# 3. Aria2c Download into /content/download\n",
                "video_file = download_with_aria2(torrent[\"torrent_url\"] or torrent[\"magnet_uri\"])\n",
                "\n",
                "# 4. Upload to DoodStream\n",
                "embed_url = upload_to_doodstream(video_file)\n",
                "\n",
                "# 5. Publish to Pantheon WordPress\n",
                "post_info = publish_movie_to_pantheon(meta, embed_url, torrent[\"quality\"])\n",
                "\n",
                "# 6. Clean up temporary video file\n",
                "if os.path.exists(video_file):\n",
                "    os.remove(video_file)\n",
                "    print(f\"[CLEANUP] Deleted temporary video: {os.path.basename(video_file)}\")\n",
                "\n",
                "print(f\"\\n🍿 Live Next.js View: http://localhost:3000/movie/{post_info.get('slug')}\")"
            ]
        }
    ]
}

os.makedirs("d:/my web_film/notebooks", exist_ok=True)
notebook_path = "d:/my web_film/notebooks/media_worker_pipeline.ipynb"
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Generated Production Colab Notebook at: {notebook_path}")
