#!/usr/bin/env python3
"""
Generates the Google Colab Notebook (.ipynb) for the production EGYMAX automation pipeline.
Includes:
- Arabic-only subtitle engine fetching highest-rated Arabic (.srt) subtitle
- FFmpeg hardsubbing function burning Arabic subtitles directly into .mp4 frames
- Native audio preservation (-c:a copy) and optimized libx264 encoding
- Aria2 directory pre-sanitization to prevent duplicate/exit status 13 errors
- Resilient DoodStream upload loop with fresh server re-allocation
- Strictly double-quoted WordPress iframe for Next.js regex compatibility
- Clean embed URL publishing without query parameters
- DevSecOps secret hygiene (Colab userdata + empty form fields)
"""
import os
import json

notebook = {
    "nbformat": 4,
    "nbformat_minor": 0,
    "metadata": {
        "colab": {
            "name": "media_worker_pipeline.ipynb",
            "provenance": [],
            "toc_visible": True
        },
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3"
        },
        "language_info": {
            "name": "python"
        }
    },
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🎬 EGYMAX Platform — Automated Cloud Ingestion Pipeline (Google Colab)\n",
                "**Production Cloud Pipeline for Headless WordPress (Pantheon) & Next.js**\n",
                "\n",
                "- **TMDB API**: High-resolution official metadata, poster, backdrop, rating, and synopsis.\n",
                "- **YTS API**: Best-quality torrent acquisition (1080p / 720p / magnet).\n",
                "- **Aria2c**: Multi-connection cloud download with pre-sanitization (clean `.mp4` container).\n",
                "- **Arabic-Only Subtitle Engine**: Searches and downloads ONLY the highest-rated Arabic (`.srt`) subtitle file via YIFY/IMDb.\n",
                "- **FFmpeg Hardsubbing (Burn-in)**: Burns Arabic subtitles directly into `.mp4` video frames with crisp outlined typography (`-c:a copy` for lossless audio).\n",
                "- **Resilient Upload Engine**: Auto-retry with fresh server allocation if large video uploads drop.\n",
                "- **Clean DoodStream Embeds**: Direct video streaming embeds without query parameters.\n",
                "- **Pantheon REST API**: Headless WordPress post publishing with strictly double-quoted 16:9 responsive embed iframe and custom metadata."
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title ⚙️ 1. Install Dependencies & Cloud Environment\n",
                "!apt-get update -qq && apt-get install -y -qq aria2 ffmpeg fonts-noto-core\n",
                "!fc-cache -fv > /dev/null 2>&1\n",
                "!pip install -q requests requests-toolbelt beautifulsoup4 python-dotenv tqdm deep-translator\n",
                "!mkdir -p /content/download /content/staging\n",
                "print(\"✅ Cloud Environment Ready: aria2c, FFmpeg, Arabic Noto fonts, and Python dependencies installed.\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 🔑 2. Cloud Configuration & Credentials (DevSecOps)\n",
                "# @markdown Configure your target Pantheon WordPress site and API keys.\n",
                "# @markdown Secrets can also be stored securely in Colab's encrypted Secrets sidebar.\n",
                "\n",
                "WP_SITE_URL = \"https://dev-movio-stream.pantheonsite.io\" # @param {type:\"string\"}\n",
                "WP_USERNAME = \"admin\" # @param {type:\"string\"}\n",
                "WP_APP_PASSWORD = \"\" # @param {type:\"string\"}\n",
                "TMDB_API_KEY = \"\" # @param {type:\"string\"}\n",
                "DOODSTREAM_API_KEY = \"\" # @param {type:\"string\"}\n",
                "\n",
                "# DevSecOps: Fallback to Colab Encrypted Secrets (key icon in sidebar)\n",
                "try:\n",
                "    from google.colab import userdata\n",
                "    WP_APP_PASSWORD = WP_APP_PASSWORD or userdata.get('WP_APP_PASSWORD')\n",
                "    TMDB_API_KEY = TMDB_API_KEY or userdata.get('TMDB_API_KEY')\n",
                "    DOODSTREAM_API_KEY = DOODSTREAM_API_KEY or userdata.get('DOODSTREAM_API_KEY')\n",
                "except Exception:\n",
                "    pass\n",
                "\n",
                "# DevSecOps: Fallback to Environment Variables\n",
                "import os\n",
                "WP_APP_PASSWORD = WP_APP_PASSWORD or os.getenv('WP_APP_PASSWORD', '')\n",
                "TMDB_API_KEY = TMDB_API_KEY or os.getenv('TMDB_API_KEY', '')\n",
                "DOODSTREAM_API_KEY = DOODSTREAM_API_KEY or os.getenv('DOODSTREAM_API_KEY', '')\n",
                "\n",
                "WP_SITE_URL = WP_SITE_URL.rstrip('/')\n",
                "NEXTJS_URL = \"https://egymax.vercel.app\"\n",
                "print(f\"✅ Target WordPress CMS: {WP_SITE_URL}\")\n",
                "print(f\"✅ Target Frontend URL: {NEXTJS_URL}\")\n",
                "print(f\"✅ Credential Status: WP Auth: {'Configured' if WP_APP_PASSWORD else 'Missing'}, TMDB: {'Configured' if TMDB_API_KEY else 'Missing'}, DoodStream: {'Configured' if DOODSTREAM_API_KEY else 'Missing'}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 🌐 3. TMDB Metadata & YTS Torrent Engine\n",
                "import os, sys, re, time, json, shutil, zipfile, io, requests, subprocess\n",
                "from urllib.parse import quote\n",
                "from requests.auth import HTTPBasicAuth\n",
                "from bs4 import BeautifulSoup\n",
                "from requests_toolbelt import MultipartEncoder, MultipartEncoderMonitor\n",
                "\n",
                "HEADERS = {\n",
                "    \"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36\",\n",
                "    \"Accept\": \"application/json, text/plain, */*\",\n",
                "}\n",
                "\n",
                "def translate_to_arabic(text):\n",
                "    if not text or not text.strip(): return ''\n",
                "    try:\n",
                "        from deep_translator import GoogleTranslator\n",
                "        res = GoogleTranslator(source='en', target='ar').translate(text)\n",
                "        if res and res.strip(): return res.strip()\n",
                "    except Exception: pass\n",
                "    try:\n",
                "        from deep_translator import MyMemoryTranslator\n",
                "        res = MyMemoryTranslator(source='en-US', target='ar-SA').translate(text)\n",
                "        if res and res.strip(): return res.strip()\n",
                "    except Exception: pass\n",
                "    return text\n",
                "\n",
                "def get_movie_metadata(title, year=None, imdb_id=None):\n",
                "    print(f\"[TMDB] Querying metadata for '{title}' (Year: {year or 'Any'}, IMDb: {imdb_id or 'None'})...\")\n",
                "    item = None\n",
                "    if imdb_id and TMDB_API_KEY:\n",
                "        try:\n",
                "            res = requests.get(f\"https://api.themoviedb.org/3/find/{imdb_id}?api_key={TMDB_API_KEY}&external_source=imdb_id\", headers=HEADERS, timeout=15).json()\n",
                "            results = res.get(\"movie_results\", [])\n",
                "            if results: item = results[0]\n",
                "        except Exception as e: print(f\"[TMDB] IMDb lookup error: {e}\")\n",
                "\n",
                "    if not item and TMDB_API_KEY:\n",
                "        try:\n",
                "            url = f\"https://api.themoviedb.org/3/search/movie?api_key={TMDB_API_KEY}&query={quote(title)}\"\n",
                "            if year: url += f\"&year={year}\"\n",
                "            res = requests.get(url, headers=HEADERS, timeout=15).json()\n",
                "            results = res.get(\"results\", [])\n",
                "            if results: item = results[0]\n",
                "        except Exception as e: print(f\"[TMDB] Search error: {e}\")\n",
                "\n",
                "    genres = \"Action, Drama\"\n",
                "    rating = \"7.5\"\n",
                "    overview_en = \"No synopsis available.\"\n",
                "    overview_ar = \"\"\n",
                "    title_ar = title\n",
                "    original_title = title\n",
                "    cast_list = []\n",
                "    poster_url = None\n",
                "    backdrop_url = None\n",
                "    final_title = title\n",
                "    final_year = year or \"2026\"\n",
                "    extracted_imdb = imdb_id\n",
                "\n",
                "    if item:\n",
                "        final_title = item.get(\"title\") or title\n",
                "        original_title = item.get(\"original_title\") or final_title\n",
                "        title_ar = final_title\n",
                "        final_year = (item.get(\"release_date\") or \"\")[:4] or final_year\n",
                "        overview_en = item.get(\"overview\") or overview_en\n",
                "        rating = str(round(item.get(\"vote_average\", 7.5), 1))\n",
                "        if item.get(\"poster_path\"): poster_url = f\"https://image.tmdb.org/t/p/original{item['poster_path']}\"\n",
                "        if item.get(\"backdrop_path\"): backdrop_url = f\"https://image.tmdb.org/t/p/original{item['backdrop_path']}\"\n",
                "        if item.get(\"id\") and TMDB_API_KEY:\n",
                "            try:\n",
                "                detail_url = f\"https://api.themoviedb.org/3/movie/{item['id']}?api_key={TMDB_API_KEY}&language=ar-SA&append_to_response=credits\"\n",
                "                d = requests.get(detail_url, headers=HEADERS, timeout=15).json()\n",
                "                if d.get(\"title\"): title_ar = d.get(\"title\")\n",
                "                if d.get(\"original_title\"): original_title = d.get(\"original_title\")\n",
                "                if d.get(\"overview\"): overview_ar = d.get(\"overview\").strip()\n",
                "                credits_cast = d.get(\"credits\", {}).get(\"cast\", [])\n",
                "                if not credits_cast:\n",
                "                    try:\n",
                "                        c_res = requests.get(f\"https://api.themoviedb.org/3/movie/{item['id']}/credits?api_key={TMDB_API_KEY}\", headers=HEADERS, timeout=10).json()\n",
                "                        credits_cast = c_res.get(\"cast\", [])\n",
                "                    except Exception: pass\n",
                "                cast_list = [c.get(\"name\") for c in credits_cast[:5] if c.get(\"name\")]\n",
                "                if \"genres\" in d and d[\"genres\"]: genres = \", \".join([g[\"name\"] for g in d[\"genres\"]])\n",
                "                extracted_imdb = d.get(\"imdb_id\") or extracted_imdb\n",
                "            except Exception: pass\n",
                "\n",
                "    if not overview_ar:\n",
                "        if overview_en and overview_en != \"No synopsis available.\":\n",
                "            overview_ar = translate_to_arabic(overview_en)\n",
                "        if not overview_ar:\n",
                "            overview_ar = \"تدور أحداث الفيلم في إطار مشوق ومثير مليء بالأحداث غير المتوقعة والمغامرات الشيقة.\"\n",
                "\n",
                "    cast_names = \"، \".join(cast_list) if cast_list else \"\"\n",
                "    if cast_names:\n",
                "        if original_title and original_title.lower() != title_ar.lower():\n",
                "            seo_intro = f\"مشاهدة وتحميل فيلم {title_ar} ({original_title}) {final_year} مترجم كامل بجودة 1080p BluRay عالية أون لاين، بطولة {cast_names}.\"\n",
                "        else:\n",
                "            seo_intro = f\"مشاهدة وتحميل فيلم {title_ar} {final_year} مترجم كامل بجودة 1080p BluRay عالية أون لاين، بطولة {cast_names}.\"\n",
                "    else:\n",
                "        if original_title and original_title.lower() != title_ar.lower():\n",
                "            seo_intro = f\"مشاهدة وتحميل فيلم {title_ar} ({original_title}) {final_year} مترجم كامل بجودة 1080p BluRay عالية أون لاين.\"\n",
                "        else:\n",
                "            seo_intro = f\"مشاهدة وتحميل فيلم {title_ar} {final_year} مترجم كامل بجودة 1080p BluRay عالية أون لاين.\"\n",
                "\n",
                "    if not poster_url:\n",
                "        poster_url = \"https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=1000&q=85\"\n",
                "\n",
                "    meta = {\n",
                "        \"title\": final_title, \"title_ar\": title_ar, \"original_title\": original_title,\n",
                "        \"year\": final_year, \"overview\": overview_en, \"overview_ar\": overview_ar,\n",
                "        \"cast\": cast_list, \"cast_names\": cast_names, \"seo_description\": seo_intro,\n",
                "        \"rating\": rating, \"genres\": genres, \"poster_url\": poster_url,\n",
                "        \"backdrop_url\": backdrop_url, \"imdb_id\": extracted_imdb\n",
                "    }\n",
                "    print(f\"[TMDB] ✅ Found: '{meta['title']}' ({meta['year']}) | Title AR: '{meta['title_ar']}' | ★ {meta['rating']} | Cast: {cast_names or 'N/A'}\")\n",
                "    return meta\n",
                "\n",
                "fetch_tmdb_metadata = get_movie_metadata\n",
                "\n",
                "def fetch_yts_torrent(title, year=None, imdb_id=None, quality=\"1080p\"):\n",
                "    query = imdb_id if imdb_id else title\n",
                "    print(f\"[YTS] Searching torrent for '{query}'...\")\n",
                "    mirrors = [\"https://yts.mx\", \"https://yts.nz\", \"https://yts.lt\", \"https://yts.do\"]\n",
                "    data = None\n",
                "    for m in mirrors:\n",
                "        try:\n",
                "            r = requests.get(f\"{m}/api/v2/list_movies.json?query_term={quote(query)}&sort_by=download_count\", headers=HEADERS, timeout=15)\n",
                "            if r.status_code == 200:\n",
                "                rj = r.json()\n",
                "                if rj.get(\"status\") == \"ok\" and rj.get(\"data\", {}).get(\"movie_count\", 0) > 0:\n",
                "                    data = rj[\"data\"]\n",
                "                    print(f\"[YTS] Connected to {m} (Matches: {data['movie_count']})\")\n",
                "                    break\n",
                "        except Exception: continue\n",
                "\n",
                "    if not data or not data.get(\"movies\"):\n",
                "        raise RuntimeError(f\"No torrents found on YTS for '{query}'.\")\n",
                "\n",
                "    movies = data[\"movies\"]\n",
                "    target = movies[0]\n",
                "    if year:\n",
                "        for mv in movies:\n",
                "            if str(mv.get(\"year\")) == str(year):\n",
                "                target = mv; break\n",
                "\n",
                "    torrents = target.get(\"torrents\", [])\n",
                "    if not torrents:\n",
                "        raise RuntimeError(f\"No torrent streams available for '{target.get('title')}'.\")\n",
                "\n",
                "    sel = None\n",
                "    for q in [quality, \"1080p\", \"720p\", \"2160p\"]:\n",
                "        for t in torrents:\n",
                "            if t.get(\"quality\", \"\").lower() == q.lower():\n",
                "                sel = t; break\n",
                "        if sel: break\n",
                "    if not sel: sel = torrents[0]\n",
                "\n",
                "    h = sel.get(\"hash\")\n",
                "    q = sel.get(\"quality\", \"1080p\")\n",
                "    trackers = [\"udp://open.demonii.com:1337/announce\", \"udp://tracker.openbittorrent.com:80\", \"udp://tracker.opentrackr.org:1337/announce\"]\n",
                "    tr_args = \"&\".join([f\"tr={quote(t)}\" for t in trackers])\n",
                "    magnet = f\"magnet:?xt=urn:btih:{h}&dn={quote(target.get('title'))}&{tr_args}\"\n",
                "    print(f\"[YTS] ✅ Selected: {q} ({sel.get('size')}) Hash: {h[:10]}...\")\n",
                "    return {\"quality\": q, \"torrent_url\": sel.get(\"url\"), \"magnet_uri\": magnet, \"size\": sel.get(\"size\")}"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 📥 4. Aria2c Download & Sanitization Engine\n",
                "def verify_video_integrity(video_path):\n",
                "    \"\"\"Run integrity check via ffprobe to verify moov atom and container readability.\"\"\"\n",
                "    if not video_path or not os.path.exists(video_path) or os.path.getsize(video_path) == 0:\n",
                "        return False\n",
                "    ffprobe_bin = shutil.which(\"ffprobe\") or \"ffprobe\"\n",
                "    probe_cmd = [ffprobe_bin, \"-v\", \"error\", \"-show_entries\", \"format=duration\", \"-of\", \"default=noprint_wrappers=1:nokey=1\", video_path]\n",
                "    try:\n",
                "        proc = subprocess.run(probe_cmd, capture_output=True, text=True, timeout=25)\n",
                "        if proc.returncode != 0:\n",
                "            print(f\"[INTEGRITY] ❌ Integrity check failed for {os.path.basename(video_path)}: {proc.stderr.strip() if proc.stderr else ''}\")\n",
                "            return False\n",
                "        dur_str = proc.stdout.strip()\n",
                "        if not dur_str or dur_str == 'N/A' or float(dur_str) <= 0:\n",
                "            return False\n",
                "        return True\n",
                "    except Exception:\n",
                "        return os.path.getsize(video_path) > (20 * 1024 * 1024)\n",
                "\n",
                "def download_with_aria2(source_uri, download_dir=\"/content/download\", staging_dir=\"/content/staging\"):\n",
                "    \"\"\"High-speed cloud download using aria2c with aggressive directory sanitization and integrity checks.\"\"\"\n",
                "    print(f\"[ARIA2] Aggressively purging and resetting directories: {download_dir} & {staging_dir}...\")\n",
                "    for d in [download_dir, staging_dir]:\n",
                "        if os.path.exists(d):\n",
                "            shutil.rmtree(d, ignore_errors=True)\n",
                "        os.makedirs(d, exist_ok=True)\n",
                "\n",
                "    print(f\"[ARIA2] Starting multi-connection download into {download_dir}...\")\n",
                "    cmd = [\n",
                "        \"aria2c\", f\"--dir={download_dir}\", \"--max-connection-per-server=16\",\n",
                "        \"--split=16\", \"--min-split-size=1M\", \"--summary-interval=10\",\n",
                "        \"--seed-time=0\", \"--follow-torrent=mem\",\n",
                "        \"--allow-overwrite=true\", \"--auto-file-renaming=false\",\n",
                "        \"--conditional-get=true\", \"--file-allocation=none\",\n",
                "        source_uri\n",
                "    ]\n",
                "    proc = subprocess.run(cmd, capture_output=False)\n",
                "    if proc.returncode != 0:\n",
                "        raise RuntimeError(f\"aria2c download failed with exit code {proc.returncode}\")\n",
                "\n",
                "    videos = []\n",
                "    for root, _, files in os.walk(download_dir):\n",
                "        for f in files:\n",
                "            if f.lower().endswith((\".mp4\", \".mkv\", \".avi\", \".webm\")):\n",
                "                p = os.path.join(root, f)\n",
                "                sz = os.path.getsize(p)\n",
                "                if sz > 0:\n",
                "                    videos.append((p, sz))\n",
                "\n",
                "    if not videos:\n",
                "        raise FileNotFoundError(f\"No video file downloaded in {download_dir}.\")\n",
                "    videos.sort(key=lambda x: x[1], reverse=True)\n",
                "    target_file = videos[0][0]\n",
                "    file_size_mb = videos[0][1] / (1024 * 1024)\n",
                "    print(f\"[ARIA2] Verifying container integrity of {os.path.basename(target_file)} ({file_size_mb:.1f} MB)...\")\n",
                "    if not verify_video_integrity(target_file):\n",
                "        raise RuntimeError(f\"Downloaded file is corrupted or incomplete; aborting upload. ({target_file})\")\n",
                "    print(f\"[ARIA2] ✅ Downloaded and verified intact: {os.path.basename(target_file)} ({file_size_mb:.1f} MB)\")\n",
                "    return target_file"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 💬 5. Arabic Subtitles & FFmpeg Hardsubbing (Burn-in)\n",
                "def read_subtitle_file_robustly(file_path):\n",
                "    \"\"\"Read subtitle file as binary bytes, strip BOMs and null bytes, and decode testing Arabic encodings in strict order.\"\"\"\n",
                "    if not file_path or not os.path.exists(file_path): return ''\n",
                "    with open(file_path, 'rb') as f:\n",
                "        raw_bytes = f.read()\n",
                "    raw_bytes = raw_bytes.replace(b'\\x00', b'')\n",
                "    encodings = ['utf-8-sig', 'utf-8', 'cp1256', 'windows-1256', 'iso-8859-6', 'utf-16', 'latin-1']\n",
                "    for enc in encodings:\n",
                "        try:\n",
                "            decoded = raw_bytes.decode(enc)\n",
                "            if any('\\u0600' <= ch <= '\\u06FF' for ch in decoded):\n",
                "                return decoded\n",
                "        except UnicodeDecodeError:\n",
                "            continue\n",
                "    return raw_bytes.decode('cp1256', errors='replace')\n",
                "\n",
                "def decode_arabic_subtitle(raw_bytes):\n",
                "    \"\"\"Decode raw subtitle bytes prioritizing Arabic encodings (utf-8-sig, utf-8, cp1256, windows-1256, iso-8859-6, utf-16, latin-1).\"\"\"\n",
                "    if not raw_bytes: return None, None\n",
                "    raw_bytes = raw_bytes.replace(b'\\x00', b'')\n",
                "    encodings = ['utf-8-sig', 'utf-8', 'cp1256', 'windows-1256', 'iso-8859-6', 'utf-16', 'latin-1']\n",
                "    for enc in encodings:\n",
                "        try:\n",
                "            candidate = raw_bytes.decode(enc)\n",
                "            if any('\\u0600' <= ch <= '\\u06FF' for ch in candidate):\n",
                "                return candidate.lstrip('\\ufeff').replace('\\r\\n', '\\n').replace('\\r', '\\n'), enc\n",
                "        except Exception: continue\n",
                "    fallback = raw_bytes.decode('cp1256', errors='replace')\n",
                "    if any('\\u0600' <= ch <= '\\u06FF' for ch in fallback):\n",
                "        return fallback.lstrip('\\ufeff').replace('\\r\\n', '\\n').replace('\\r', '\\n'), 'cp1256'\n",
                "    return None, None\n",
                "\n",
                "def download_subtitles_for_imdb(imdb_id, output_dir=\"/content/download\"):\n",
                "    \"\"\"Search and download ONLY the highest-rated Arabic (.srt) subtitle file.\"\"\"\n",
                "    if not imdb_id:\n",
                "        print(\"[SUBS] No IMDb ID available; skipping Arabic subtitle download.\")\n",
                "        return None\n",
                "\n",
                "    subs_dir = os.path.join(output_dir, \"subtitles\")\n",
                "    os.makedirs(subs_dir, exist_ok=True)\n",
                "    headers = {\"User-Agent\": \"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36\"}\n",
                "    print(f\"[SUBS] Searching highest-rated Arabic subtitle for IMDb ID '{imdb_id}'...\")\n",
                "    arabic_sub_url = None\n",
                "\n",
                "    # 1. Try JSON endpoint\n",
                "    try:\n",
                "        r = requests.get(f\"https://api.yifysubtitles.ch/subs/{imdb_id}\", headers=headers, timeout=6)\n",
                "        if r.status_code == 200:\n",
                "            data = r.json().get(\"subs\", {}).get(imdb_id, {})\n",
                "            arabic_subs = data.get(\"arabic\", [])\n",
                "            if arabic_subs:\n",
                "                sorted_subs = sorted(arabic_subs, key=lambda x: x.get(\"rating\", 0), reverse=True)\n",
                "                arabic_sub_url = sorted_subs[0].get(\"url\")\n",
                "                if arabic_sub_url:\n",
                "                    print(f\"[SUBS] Found Arabic subtitle via JSON API (Rating: {sorted_subs[0].get('rating', 'N/A')})\")\n",
                "    except Exception as e:\n",
                "        print(f\"[SUBS] JSON API notice: {e}\")\n",
                "\n",
                "    # 2. Resilient fallback to HTML mirrors\n",
                "    if not arabic_sub_url:\n",
                "        mirrors = [\n",
                "            f\"https://yifysubtitles.ch/movie-imdb/{imdb_id}\",\n",
                "            f\"https://yts-subs.com/movie-imdb/{imdb_id}\",\n",
                "            f\"https://yifysubtitles.org/movie-imdb/{imdb_id}\"\n",
                "        ]\n",
                "        for mirror in mirrors:\n",
                "            try:\n",
                "                r = requests.get(mirror, headers=headers, timeout=10)\n",
                "                if r.status_code == 200:\n",
                "                    soup = BeautifulSoup(r.text, \"html.parser\")\n",
                "                    for tr in soup.find_all(\"tr\"):\n",
                "                        lang_text = \"\"\n",
                "                        lang_tag = tr.find(class_=\"sub-lang\")\n",
                "                        if lang_tag:\n",
                "                            lang_text = lang_tag.text.strip().lower()\n",
                "                        else:\n",
                "                            for td in tr.find_all(\"td\"):\n",
                "                                if \"arabic\" in td.text.strip().lower():\n",
                "                                    lang_text = \"arabic\"\n",
                "                                    break\n",
                "                        # Strictly match Arabic rows - NEVER fall back to top/first row\n",
                "                        if lang_text == \"arabic\" or \"arabic\" in lang_text:\n",
                "                            a = tr.find(\"a\", href=True)\n",
                "                            if a and \"/subtitles/\" in a[\"href\"]:\n",
                "                                arabic_sub_url = a[\"href\"]\n",
                "                                print(f\"[SUBS] Found Arabic subtitle on mirror: {mirror}\")\n",
                "                                break\n",
                "                    if arabic_sub_url: break\n",
                "            except Exception: continue\n",
                "\n",
                "    if not arabic_sub_url:\n",
                "        print(f\"[SUBS] No Arabic subtitles found for IMDb ID {imdb_id}.\")\n",
                "        return None\n",
                "\n",
                "    # 3. Download .zip archive and extract Arabic .srt with HTML inspection and mirror fallback\n",
                "    slug = arabic_sub_url.rstrip(\"/\").split(\"/\")[-1]\n",
                "    zip_mirrors = [\"https://yifysubtitles.ch\", \"https://yts-subs.com\", \"https://yifysubtitles.org\"]\n",
                "    for zip_base in zip_mirrors:\n",
                "        zip_url = f\"{zip_base}/subtitle/{slug}.zip\"\n",
                "        req_headers = {\"User-Agent\": headers[\"User-Agent\"], \"Referer\": f\"{zip_base}/subtitles/{slug}\"}\n",
                "        try:\n",
                "            zr = requests.get(zip_url, headers=req_headers, timeout=15)\n",
                "            if zr.status_code == 200:\n",
                "                raw_data = zr.content.strip()\n",
                "                # Inspect downloaded content: check if an HTML error / anti-bot page was returned\n",
                "                if raw_data.lower().startswith(b\"<!doctype html\") or raw_data.lower().startswith(b\"<html\") or b\"<body\" in raw_data[:500].lower():\n",
                "                    print(f\"[SUBS] ⚠️ Mirror {zip_base} returned HTML anti-bot/error page instead of ZIP. Trying next mirror...\")\n",
                "                    continue\n",
                "\n",
                "                with zipfile.ZipFile(io.BytesIO(zr.content)) as z:\n",
                "                    srt_files = [f for f in z.namelist() if f.lower().endswith(\".srt\") and not f.startswith(\"__MACOSX\")]\n",
                "                    if not srt_files:\n",
                "                        print(f\"[SUBS] No .srt files found in archive from {zip_base}.\")\n",
                "                        continue\n",
                "\n",
                "                    selected_text = None\n",
                "                    selected_encoding = None\n",
                "                    target_filename = None\n",
                "\n",
                "                    # Prioritize .srt files matching *ara* or *arabic* in their filename\n",
                "                    sorted_files = sorted(srt_files, key=lambda x: 0 if (\"arabic\" in x.lower() or \"ara\" in x.lower()) else 1)\n",
                "                    for fname in sorted_files:\n",
                "                        f_bytes = z.read(fname)\n",
                "                        decoded_text, detected_enc = decode_arabic_subtitle(f_bytes)\n",
                "                        if decoded_text:\n",
                "                            selected_text = decoded_text\n",
                "                            selected_encoding = detected_enc\n",
                "                            target_filename = fname\n",
                "                            break\n",
                "\n",
                "                    if not selected_text:\n",
                "                        print(f\"[SUBS] None of the subtitle files in {slug}.zip contain Arabic characters across tested encodings.\")\n",
                "                        continue\n",
                "\n",
                "                    out_srt = os.path.join(subs_dir, f\"{imdb_id}_ara.srt\")\n",
                "                    with open(out_srt, \"w\", encoding=\"utf-8\", newline=\"\\n\") as sf:\n",
                "                        sf.write(selected_text)\n",
                "\n",
                "                    print(f\"[SUBS] ℹ️ Subtitle decoded using '{selected_encoding}' and re-encoded to UTF-8.\")\n",
                "                    print(f\"[SUBS] ✅ Extracted and verified Arabic subtitle -> {os.path.basename(out_srt)}\")\n",
                "                    return out_srt\n",
                "        except Exception as e:\n",
                "            print(f\"[SUBS] Mirror {zip_base} notice: {e}\")\n",
                "            continue\n",
                "\n",
                "    print(f\"[SUBS] Failed downloading or verifying Arabic subtitle for {imdb_id}.\")\n",
                "    return None\n",
                "\n",
                "def probe_video_properties(video_path):\n",
                "    \"\"\"\n",
                "    Probe video properties using ffprobe to extract source video bitrate (bps) and duration (seconds).\n",
                "    Falls back to calculating bitrate from file size and duration if not directly reported in streams/format.\n",
                "    \"\"\"\n",
                "    source_bitrate = 0\n",
                "    duration = 0.0\n",
                "    file_size_bytes = os.path.getsize(video_path) if os.path.exists(video_path) else 0\n",
                "\n",
                "    ffprobe_bin = shutil.which(\"ffprobe\") or \"ffprobe\"\n",
                "    try:\n",
                "        probe_cmd = [\n",
                "            ffprobe_bin, \"-v\", \"error\",\n",
                "            \"-select_streams\", \"v:0\",\n",
                "            \"-show_entries\", \"stream=bit_rate,duration:format=bit_rate,duration\",\n",
                "            \"-of\", \"json\",\n",
                "            video_path\n",
                "        ]\n",
                "        proc = subprocess.run(probe_cmd, capture_output=True, text=True, timeout=20)\n",
                "        if proc.returncode == 0 and proc.stdout:\n",
                "            data = json.loads(proc.stdout)\n",
                "            streams = data.get(\"streams\", [])\n",
                "            fmt = data.get(\"format\", {})\n",
                "\n",
                "            # Extract duration: stream first, then format\n",
                "            if streams and streams[0].get(\"duration\") not in (None, \"N/A\"):\n",
                "                try:\n",
                "                    duration = float(streams[0][\"duration\"])\n",
                "                except (ValueError, TypeError):\n",
                "                    pass\n",
                "            if duration <= 0 and fmt.get(\"duration\") not in (None, \"N/A\"):\n",
                "                try:\n",
                "                    duration = float(fmt[\"duration\"])\n",
                "                except (ValueError, TypeError):\n",
                "                    pass\n",
                "\n",
                "            # Extract bitrate in kbps: stream first, then format\n",
                "            if streams and streams[0].get(\"bit_rate\") not in (None, \"N/A\"):\n",
                "                try:\n",
                "                    raw_br = float(streams[0][\"bit_rate\"])\n",
                "                    source_bitrate = int(raw_br / 1000) if raw_br > 50000 else int(raw_br)\n",
                "                except (ValueError, TypeError):\n",
                "                    pass\n",
                "            if source_bitrate <= 0 and fmt.get(\"bit_rate\") not in (None, \"N/A\"):\n",
                "                try:\n",
                "                    raw_br = float(fmt[\"bit_rate\"])\n",
                "                    source_bitrate = int(raw_br / 1000) if raw_br > 50000 else int(raw_br)\n",
                "                except (ValueError, TypeError):\n",
                "                    pass\n",
                "    except Exception as e:\n",
                "        print(f\"[HARDSUB] ffprobe notice: {e}\")\n",
                "\n",
                "    # Fallback: calculate bitrate from file size and duration (in kbps)\n",
                "    if source_bitrate <= 0 and duration > 0 and file_size_bytes > 0:\n",
                "        source_bitrate = int((file_size_bytes * 8) / (duration * 1000))\n",
                "\n",
                "    # Safe defaults if probe could not determine properties (in kbps)\n",
                "    if source_bitrate <= 0:\n",
                "        source_bitrate = 2500  # Default ~2500 kbps (2.5 Mbps)\n",
                "    if duration <= 0:\n",
                "        duration = 7200.0  # Default ~2 hours\n",
                "\n",
                "    return source_bitrate, duration\n",
                "\n",
                "def apply_ass_style(ass_text):\n",
                "    \"\"\"Ensure ASS uses 1080p canvas (PlayResX: 1920, PlayResY: 1080) and high-visibility Arabic Style: Default.\"\"\"\n",
                "    if not ass_text: return ''\n",
                "    target_style = 'Style: Default,Noto Sans Arabic,76,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,3.2,1,2,20,20,45,1'\n",
                "    if '[Script Info]' in ass_text:\n",
                "        ass_text = re.sub(r'PlayResX:\\s*\\d+', 'PlayResX: 1920', ass_text, flags=re.IGNORECASE)\n",
                "        ass_text = re.sub(r'PlayResY:\\s*\\d+', 'PlayResY: 1080', ass_text, flags=re.IGNORECASE)\n",
                "        ass_text = re.sub(r'ScaledBorderAndShadow:\\s*\\w+', 'ScaledBorderAndShadow: yes', ass_text, flags=re.IGNORECASE)\n",
                "        if 'PlayResX:' not in ass_text: ass_text = ass_text.replace('[Script Info]', '[Script Info]\\nPlayResX: 1920', 1)\n",
                "        if 'PlayResY:' not in ass_text: ass_text = ass_text.replace('[Script Info]', '[Script Info]\\nPlayResY: 1080', 1)\n",
                "        if 'ScaledBorderAndShadow:' not in ass_text: ass_text = ass_text.replace('[Script Info]', '[Script Info]\\nScaledBorderAndShadow: yes', 1)\n",
                "    else:\n",
                "        ass_text = f'[Script Info]\\nScriptType: v4.00+\\nPlayResX: 1920\\nPlayResY: 1080\\nScaledBorderAndShadow: yes\\n\\n{ass_text}'\n",
                "    if re.search(r'^Style:\\s*Default,.*$', ass_text, flags=re.MULTILINE):\n",
                "        ass_text = re.sub(r'^Style:\\s*Default,.*$', target_style, ass_text, flags=re.MULTILINE)\n",
                "    elif '[V4+ Styles]' in ass_text:\n",
                "        if 'Format:' in ass_text: ass_text = re.sub(r'(Format:[^\\n]*\\n)', rf'\\1{target_style}\\n', ass_text, count=1)\n",
                "        else: ass_text = ass_text.replace('[V4+ Styles]', f'[V4+ Styles]\\n{target_style}', 1)\n",
                "    else:\n",
                "        v4_section = f'\\n[V4+ Styles]\\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\\n{target_style}\\n\\n'\n",
                "        if '[Events]' in ass_text: ass_text = ass_text.replace('[Events]', f'{v4_section}[Events]', 1)\n",
                "        else: ass_text = f'{v4_section}{ass_text}'\n",
                "    return ass_text\n",
                "\n",
                "def convert_srt_to_ass(srt_text, srt_path=None):\n",
                "    \"\"\"Convert SRT to ASS on 1080p canvas with high-visibility Arabic style. Resilient to null bytes, bidi marks, broken blocks.\"\"\"\n",
                "    if not srt_text: return ''\n",
                "    raw_text = srt_text.replace('\\x00', '').lstrip('\\ufeff\\ufffe').replace('\\r\\n', '\\n').replace('\\r', '\\n')\n",
                "    bidi_pattern = re.compile(r'[\\u200e\\u200f\\u061c\\u200b-\\u200d\\u202a-\\u202e\\u2066-\\u2069\\ufeff]')\n",
                "    cleaned = bidi_pattern.sub('', raw_text).strip()\n",
                "    if not cleaned: return ''\n",
                "    header_lines = [\n",
                "        \"[Script Info]\",\n",
                "        \"ScriptType: v4.00+\",\n",
                "        \"PlayResX: 1920\",\n",
                "        \"PlayResY: 1080\",\n",
                "        \"WrapStyle: 0\",\n",
                "        \"ScaledBorderAndShadow: yes\",\n",
                "        \"\",\n",
                "        \"[V4+ Styles]\",\n",
                "        \"Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\",\n",
                "        \"Style: Default,Noto Sans Arabic,76,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,1,0,0,0,100,100,0,0,1,3.2,1,2,20,20,45,1\",\n",
                "        \"\",\n",
                "        \"[Events]\",\n",
                "        \"Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\",\n",
                "    ]\n",
                "    ass_header = '\\n'.join(header_lines) + '\\n'\n",
                "    time_pattern = re.compile(r'(\\d{1,2}:\\d{2}:\\d{2}[,.]\\d{1,3})\\s*(?:-->|->|—>|–>)\\s*(\\d{1,2}:\\d{2}:\\d{2}[,.]\\d{1,3})')\n",
                "    def _srt_ts_to_ass(ts):\n",
                "        ts = ts.replace(',', '.')\n",
                "        parts = ts.split(':')\n",
                "        h, mi = int(parts[0]), int(parts[1])\n",
                "        sec_parts = parts[2].split('.')\n",
                "        s = int(sec_parts[0])\n",
                "        ms_raw = sec_parts[1] if len(sec_parts) > 1 else '0'\n",
                "        cs = int(ms_raw.ljust(3, '0')[:3]) // 10\n",
                "        return f'{h}:{mi:02d}:{s:02d}.{cs:02d}'\n",
                "    def _clean_line(line):\n",
                "        c = re.sub(r'<[^>]+>', '', line.strip())\n",
                "        c = bidi_pattern.sub('', c)\n",
                "        return c\n",
                "    blocks = re.split(r'\\n\\s*\\n', cleaned)\n",
                "    dialogues = []\n",
                "    for block in blocks:\n",
                "        lines = block.strip().split('\\n')\n",
                "        if len(lines) < 2: continue\n",
                "        tm = None\n",
                "        timing_idx = -1\n",
                "        for i, line in enumerate(lines):\n",
                "            tm = time_pattern.search(line)\n",
                "            if tm:\n",
                "                timing_idx = i\n",
                "                break\n",
                "        if not tm or timing_idx < 0: continue\n",
                "        start_ass = _srt_ts_to_ass(tm.group(1))\n",
                "        end_ass = _srt_ts_to_ass(tm.group(2))\n",
                "        text_parts = [_clean_line(tl) for tl in lines[timing_idx + 1:] if _clean_line(tl)]\n",
                "        if not text_parts: continue\n",
                "        text = '\\\\N'.join(text_parts)\n",
                "        dialogues.append(f'Dialogue: 0,{start_ass},{end_ass},Default,,0,0,0,,{text}')\n",
                "    # Fallback Sequential Parser: if block splitting yielded 0 entries\n",
                "    if not dialogues:\n",
                "        lines = cleaned.split('\\n')\n",
                "        current_start = None\n",
                "        current_end = None\n",
                "        current_text_parts = []\n",
                "        def _append_seq_dialogue():\n",
                "            if current_start and current_end and current_text_parts:\n",
                "                start_ass = _srt_ts_to_ass(current_start)\n",
                "                end_ass = _srt_ts_to_ass(current_end)\n",
                "                text = '\\\\N'.join(current_text_parts)\n",
                "                dialogues.append(f'Dialogue: 0,{start_ass},{end_ass},Default,,0,0,0,,{text}')\n",
                "        for line in lines:\n",
                "            line_str = line.strip()\n",
                "            if not line_str: continue\n",
                "            tm = time_pattern.search(line_str)\n",
                "            if tm:\n",
                "                _append_seq_dialogue()\n",
                "                current_start = tm.group(1)\n",
                "                current_end = tm.group(2)\n",
                "                current_text_parts = []\n",
                "            elif current_start is not None:\n",
                "                cleaned_text = _clean_line(line_str)\n",
                "                if cleaned_text and not cleaned_text.isdigit():\n",
                "                    current_text_parts.append(cleaned_text)\n",
                "        _append_seq_dialogue()\n",
                "    if dialogues:\n",
                "        return ass_header + '\\n'.join(dialogues) + '\\n'\n",
                "    # Fallback Native FFmpeg Engine\n",
                "    ffmpeg_bin = shutil.which('ffmpeg')\n",
                "    if ffmpeg_bin:\n",
                "        import tempfile\n",
                "        temp_src = srt_path\n",
                "        need_rm = False\n",
                "        if not temp_src or not os.path.exists(temp_src):\n",
                "            try:\n",
                "                with tempfile.NamedTemporaryFile('w', encoding='utf-8', suffix='.srt', delete=False) as tf:\n",
                "                    tf.write(cleaned)\n",
                "                    temp_src = tf.name\n",
                "                need_rm = True\n",
                "            except Exception: temp_src = None\n",
                "        if temp_src and os.path.exists(temp_src):\n",
                "            temp_ass = temp_src + '.ass'\n",
                "            try:\n",
                "                subprocess.run([ffmpeg_bin, '-y', '-sub_charenc', 'UTF-8', '-i', temp_src, temp_ass], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL, check=False)\n",
                "                if os.path.exists(temp_ass) and os.path.getsize(temp_ass) > 0:\n",
                "                    with open(temp_ass, 'r', encoding='utf-8', errors='replace') as af:\n",
                "                        raw_ass = af.read()\n",
                "                    if 'Dialogue:' in raw_ass: return apply_ass_style(raw_ass)\n",
                "            except Exception: pass\n",
                "            finally:\n",
                "                if need_rm and temp_src and os.path.exists(temp_src):\n",
                "                    try: os.remove(temp_src)\n",
                "                    except Exception: pass\n",
                "                if os.path.exists(temp_ass):\n",
                "                    try: os.remove(temp_ass)\n",
                "                    except Exception: pass\n",
                "    return ''\n",
                "\n",
                "def burn_arabic_subtitles(video_path, srt_path):\n",
                "    \"\"\"\n",
                "    Burn Arabic subtitles into video frames using FFmpeg.\n",
                "    Enforces clean UTF-8 encoding (prioritizing windows-1256/cp1256 conversion before latin1),\n",
                "    sanitizes paths, executes FFmpeg from a flat staging directory, and dynamically controls\n",
                "    bitrate with NVENC p6/cq20-22 to strictly cap output under 4200 MB for all movie lengths.\n",
                "    \"\"\"\n",
                "    if not video_path or not os.path.exists(video_path):\n",
                "        print(\"[HARDSUB] Video path is invalid or missing.\")\n",
                "        return video_path\n",
                "\n",
                "    if not verify_video_integrity(video_path):\n",
                "        raise RuntimeError(f\"Downloaded file is corrupted or incomplete; aborting upload. ({video_path})\")\n",
                "\n",
                "    if not srt_path or not os.path.exists(srt_path):\n",
                "        print(\"[HARDSUB] ⚠️ No Arabic subtitle provided or file missing; using original video as fallback.\")\n",
                "        return video_path\n",
                "\n",
                "    ffmpeg_bin = shutil.which(\"ffmpeg\")\n",
                "    if not ffmpeg_bin:\n",
                "        print(\"[HARDSUB] ⚠️ ffmpeg not found in PATH; skipping hardsubbing and using raw video.\")\n",
                "        return video_path\n",
                "\n",
                "    # 1. Force UTF-8 conversion testing priority encodings: utf-8-sig, utf-8, cp1256, windows-1256, iso-8859-6, utf-16, latin-1\n",
                "    try:\n",
                "        clean_sub_text = read_subtitle_file_robustly(srt_path)\n",
                "        if not clean_sub_text or not any('\\u0600' <= ch <= '\\u06FF' for ch in clean_sub_text):\n",
                "            print(f\"[HARDSUB] ⚠️ Subtitle '{srt_path}' contains no Arabic Unicode characters across tested encodings; using original video.\")\n",
                "            return video_path\n",
                "        print(\"[SUBS] ℹ️ Subtitle decoded robustly and verified to contain Arabic characters.\")\n",
                "    except Exception as e:\n",
                "        print(f\"[HARDSUB] ⚠️ Error validating subtitle encoding: {e}; using raw video.\")\n",
                "        return video_path\n",
                "\n",
                "    # 2. Implement Flat Staging Directory Architecture\n",
                "    staging_dir = \"/content/staging\" if os.path.exists(\"/content\") else os.path.abspath(\"./staging_temp\")\n",
                "    os.makedirs(staging_dir, exist_ok=True)\n",
                "\n",
                "    staged_input = os.path.join(staging_dir, \"input_video.mp4\")\n",
                "    staged_sub = os.path.join(staging_dir, \"sub.ass\")\n",
                "    staged_output = os.path.join(staging_dir, \"output_subbed.mp4\")\n",
                "\n",
                "    # Clean previous staging artifacts if present\n",
                "    for p in [staged_input, staged_sub, staged_output]:\n",
                "        if os.path.exists(p) or os.path.islink(p):\n",
                "            try: os.remove(p)\n",
                "            except Exception: pass\n",
                "\n",
                "    # Stage cleaned SRT file as strict UTF-8 for native FFmpeg conversion\n",
                "    staged_clean_srt = os.path.join(staging_dir, 'clean_sub.srt')\n",
                "    try:\n",
                "        with open(staged_clean_srt, 'w', encoding='utf-8', newline='\\n') as csf:\n",
                "            csf.write(clean_sub_text)\n",
                "    except Exception as e:\n",
                "        print(f\"[HARDSUB] ⚠️ Could not write {staged_clean_srt}: {e}\")\n",
                "        staged_clean_srt = srt_path\n",
                "\n",
                "    # Convert SRT → ASS format (bypasses FFmpeg SRT demuxer 'Unable to open' errors)\n",
                "    ass_content = convert_srt_to_ass(clean_sub_text, staged_clean_srt)\n",
                "    if not ass_content or 'Dialogue:' not in ass_content:\n",
                "        print('[HARDSUB] ⚠️ Python parser yielded 0 dialogues; invoking native FFmpeg CLI conversion engine...')\n",
                "        try:\n",
                "            subprocess.run(['ffmpeg', '-y', '-sub_charenc', 'UTF-8', '-i', staged_clean_srt, staged_sub], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)\n",
                "            if os.path.exists(staged_sub) and os.path.getsize(staged_sub) > 0:\n",
                "                with open(staged_sub, 'r', encoding='utf-8', errors='replace') as af:\n",
                "                    ass_content = apply_ass_style(af.read())\n",
                "                with open(staged_sub, 'w', encoding='utf-8', newline='\\n') as out_sf:\n",
                "                    out_sf.write(ass_content)\n",
                "                print(f'[HARDSUB] ✅ Native FFmpeg subtitle conversion succeeded: {staged_sub}')\n",
                "        except Exception as e:\n",
                "            print(f'[HARDSUB] ⚠️ Native FFmpeg conversion error: {e}')\n",
                "\n",
                "    if not ass_content or 'Dialogue:' not in ass_content:\n",
                "        print('[HARDSUB] ⚠️ SRT→ASS conversion produced no valid subtitle entries; using original video.')\n",
                "        return video_path\n",
                "\n",
                "    # Stage the ASS subtitle file inside staging_dir (if not already written)\n",
                "    try:\n",
                "        with open(staged_sub, 'w', encoding='utf-8', newline='\\n') as out_sf:\n",
                "            out_sf.write(ass_content)\n",
                "        print(f\"[HARDSUB] Staged subtitle (SRT→ASS converted, {len(ass_content)} bytes): {staged_sub}\")\n",
                "    except Exception as e:\n",
                "        print(f\"[HARDSUB] ⚠️ Could not write {staged_sub}: {e}\")\n",
                "        return video_path\n",
                "\n",
                "    # Stage input video via symlink (instant & zero disk overhead on Linux/Colab)\n",
                "    video_abs = os.path.abspath(video_path)\n",
                "    ffmpeg_input = \"input_video.mp4\"\n",
                "    try:\n",
                "        os.symlink(video_abs, staged_input)\n",
                "        print(f\"[HARDSUB] Staged video symlinked: {staged_input} -> {video_abs}\")\n",
                "    except Exception as e:\n",
                "        print(f\"[HARDSUB] Symlink notice: {e}; referencing input path directly.\")\n",
                "        ffmpeg_input = video_abs\n",
                "\n",
                "    # 3. ASS subtitle filter with dimension and pixel format stabilization\n",
                "    sub_abs = os.path.abspath(staged_sub).replace('\\\\', '/')\n",
                "    sub_filter_path = sub_abs.replace(':', '\\\\:')\n",
                "    subtitles_filter = f\"scale=trunc(iw/2)*2:trunc(ih/2)*2,format=yuv420p,ass='{sub_filter_path}'\"\n",
                "\n",
                "    # 4. Strict Bitrate & Audio Budgeting (guarantee final container strictly under 4200 MB)\n",
                "    source_bitrate, duration = probe_video_properties(video_abs)\n",
                "    if source_bitrate > 50000:\n",
                "        source_bitrate = int(source_bitrate / 1000)\n",
                "\n",
                "    MAX_CONTAINER_MB = 4200\n",
                "    if duration > 0:\n",
                "        total_max_kbps = int((MAX_CONTAINER_MB * 8192) / duration)\n",
                "        ceiling_video_kbps = max(1200, total_max_kbps - 400)\n",
                "        target_bitrate = min(int(source_bitrate * 1.05), ceiling_video_kbps)\n",
                "        max_rate = min(int(target_bitrate * 1.25), ceiling_video_kbps)\n",
                "    else:\n",
                "        ceiling_video_kbps = 2500\n",
                "        target_bitrate = min(int(source_bitrate * 1.05), ceiling_video_kbps)\n",
                "        max_rate = min(int(target_bitrate * 1.25), ceiling_video_kbps)\n",
                "\n",
                "    bufsize = max_rate * 2\n",
                "    cq_val = 22 if duration > 9000 else 20\n",
                "\n",
                "    print(f\"[HARDSUB] Dynamic Bitrate Profile: duration={duration:.0f}s, cq={cq_val}, source={source_bitrate} kbps -> target={target_bitrate}k, maxrate={max_rate}k (ceiling={ceiling_video_kbps}k, bufsize={bufsize}k, max 4200MB)\")\n",
                "\n",
                "    print(f\"[HARDSUB] Burning Arabic subtitles into frames (NVENC p6/cq{cq_val}): output_subbed.mp4 in {staging_dir}...\")\n",
                "    cmd = [\n",
                "        \"ffmpeg\", \"-y\",\n",
                "        \"-i\", ffmpeg_input,\n",
                "        \"-vf\", subtitles_filter,\n",
                "        \"-c:v\", \"h264_nvenc\",\n",
                "        \"-preset\", \"p6\",\n",
                "        \"-tune\", \"hq\",\n",
                "        \"-rc\", \"vbr\",\n",
                "        \"-cq\", str(cq_val),\n",
                "        \"-b:v\", f\"{target_bitrate}k\",\n",
                "        \"-maxrate\", f\"{max_rate}k\",\n",
                "        \"-bufsize\", f\"{bufsize}k\",\n",
                "        \"-pix_fmt\", \"yuv420p\",\n",
                "        \"-c:a\", \"copy\",\n",
                "        \"output_subbed.mp4\"\n",
                "    ]\n",
                "    proc = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, cwd=staging_dir)\n",
                "    if proc.returncode != 0:\n",
                "        err_snippet = proc.stderr[-300:] if proc.stderr else \"\"\n",
                "        print(f\"[HARDSUB] NVENC hardsubbing error ({proc.returncode}): {err_snippet}. Attempting CPU fallback (libx264 ultrafast / crf {cq_val})...\")\n",
                "        cmd_cpu = [\n",
                "            \"ffmpeg\", \"-y\",\n",
                "            \"-i\", ffmpeg_input,\n",
                "            \"-vf\", subtitles_filter,\n",
                "            \"-c:v\", \"libx264\",\n",
                "            \"-preset\", \"ultrafast\",\n",
                "            \"-crf\", str(cq_val),\n",
                "            \"-b:v\", f\"{target_bitrate}k\",\n",
                "            \"-maxrate\", f\"{max_rate}k\",\n",
                "            \"-bufsize\", f\"{bufsize}k\",\n",
                "            \"-pix_fmt\", \"yuv420p\",\n",
                "            \"-c:a\", \"copy\",\n",
                "            \"output_subbed.mp4\"\n",
                "        ]\n",
                "        proc_cpu = subprocess.run(cmd_cpu, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, cwd=staging_dir)\n",
                "        if proc_cpu.returncode != 0:\n",
                "            cpu_snippet = proc_cpu.stderr[-300:] if proc_cpu.stderr else \"\"\n",
                "            print(f\"[HARDSUB] ❌ CPU fallback failed ({proc_cpu.returncode}): {cpu_snippet}\")\n",
                "            for p in [staged_input, staged_sub]:\n",
                "                if os.path.exists(p) or os.path.islink(p):\n",
                "                    try: os.remove(p)\n",
                "                    except Exception: pass\n",
                "            if verify_video_integrity(video_path):\n",
                "                print(\"[HARDSUB] Falling back to intact original video file.\")\n",
                "                return video_path\n",
                "            else:\n",
                "                raise RuntimeError(f\"Downloaded file is corrupted or incomplete; aborting upload. ({video_path})\")\n",
                "\n",
                "    # Clean up staging input and subtitle file\n",
                "    for p in [staged_input, staged_sub]:\n",
                "        if os.path.exists(p) or os.path.islink(p):\n",
                "            try: os.remove(p)\n",
                "            except Exception: pass\n",
                "\n",
                "    if os.path.exists(staged_output) and os.path.getsize(staged_output) > 0:\n",
                "        if verify_video_integrity(staged_output):\n",
                "            mb = os.path.getsize(staged_output) / (1024 * 1024)\n",
                "            print(f\"[HARDSUB] ✅ Hardsubbing complete and verified intact! Video: {staged_output} ({mb:.1f} MB)\")\n",
                "            return staged_output\n",
                "        else:\n",
                "            print(f\"[HARDSUB] ⚠️ Hardsubbed output failed integrity verification! Checking original video...\")\n",
                "            if verify_video_integrity(video_path):\n",
                "                return video_path\n",
                "            raise RuntimeError(f\"Downloaded file is corrupted or incomplete; aborting upload. ({video_path})\")\n",
                "\n",
                "    if verify_video_integrity(video_path):\n",
                "        return video_path\n",
                "    raise RuntimeError(f\"Downloaded file is corrupted or incomplete; aborting upload. ({video_path})\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title ☁️ 6. Resilient DoodStream Upload Engine\n",
                "def upload_to_doodstream(video_path, max_retries=3):\n",
                "    \"\"\"Chunked streaming upload to DoodStream API with retry loop and new server allocation on disconnect.\"\"\"\n",
                "    if not DOODSTREAM_API_KEY:\n",
                "        raise ValueError(\"DOODSTREAM_API_KEY is not configured. Please supply an API key in Cell 2.\")\n",
                "\n",
                "    fname = os.path.basename(video_path)\n",
                "    size_mb = os.path.getsize(video_path) / (1024 * 1024)\n",
                "    last_err = None\n",
                "\n",
                "    for attempt in range(1, max_retries + 1):\n",
                "        try:\n",
                "            print(f\"[DOOD] Requesting fresh upload server (Attempt {attempt}/{max_retries})...\")\n",
                "            srv_resp = requests.get(\"https://doodapi.com/api/upload/server\", params={\"key\": DOODSTREAM_API_KEY}, timeout=30).json()\n",
                "            if srv_resp.get(\"status\") != 200 or not srv_resp.get(\"result\"):\n",
                "                raise RuntimeError(f\"Failed to allocate upload server: {srv_resp}\")\n",
                "\n",
                "            upload_url = srv_resp[\"result\"]\n",
                "            print(f\"[DOOD] Uploading '{fname}' ({size_mb:.1f} MB) via {upload_url[:45]}...\")\n",
                "\n",
                "            with open(video_path, 'rb') as f:\n",
                "                encoder = MultipartEncoder(fields={'api_key': DOODSTREAM_API_KEY, 'file': (fname, f, 'video/mp4')})\n",
                "                last_pct = [-1]\n",
                "                def progress(m):\n",
                "                    pct = int((m.bytes_read / m.len) * 100)\n",
                "                    if pct % 10 == 0 and pct != last_pct[0]:\n",
                "                        last_pct[0] = pct\n",
                "                        print(f\"  [Upload Progress] {pct}% ({m.bytes_read/(1024*1024):.1f} MB / {m.len/(1024*1024):.1f} MB)\", flush=True)\n",
                "                monitor = MultipartEncoderMonitor(encoder, progress)\n",
                "                resp = requests.post(upload_url, data=monitor, headers={'Content-Type': monitor.content_type}, timeout=7200).json()\n",
                "\n",
                "            if resp.get(\"status\") != 200:\n",
                "                raise RuntimeError(f\"DoodStream rejected upload: {resp}\")\n",
                "\n",
                "            res = resp[\"result\"]\n",
                "            code = res[0][\"filecode\"] if isinstance(res, list) else res[\"filecode\"]\n",
                "            embed = f\"https://doodstream.com/e/{code}\"\n",
                "            print(f\"[DOOD] ✅ Upload successful! Embed: {embed}\")\n",
                "            return embed\n",
                "        except Exception as e:\n",
                "            last_err = e\n",
                "            print(f\"[DOOD] Upload attempt {attempt} notice: {e.__class__.__name__}: {e}\")\n",
                "            if attempt < max_retries:\n",
                "                wait_sec = attempt * 7\n",
                "                print(f\"[DOOD] Waiting {wait_sec}s before requesting a fresh upload server...\")\n",
                "                time.sleep(wait_sec)\n",
                "\n",
                "    raise RuntimeError(f\"DoodStream upload failed after {max_retries} attempts. Last error: {last_err}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 📝 7. Headless WordPress Publisher (Auto-Categorization & Strict Double Quotes)\n",
                "GENRE_MAP = {\n",
                "    \"Action\": (\"أكشن\", \"action\"),\n",
                "    \"Adventure\": (\"مغامرة\", \"adventure\"),\n",
                "    \"Animation\": (\"رسوم متحركة\", \"animation\"),\n",
                "    \"Comedy\": (\"كوميديا\", \"comedy\"),\n",
                "    \"Crime\": (\"جريمة\", \"crime\"),\n",
                "    \"Documentary\": (\"وثائقي\", \"documentary\"),\n",
                "    \"Drama\": (\"دراما\", \"drama\"),\n",
                "    \"Family\": (\"عائلي\", \"family\"),\n",
                "    \"Fantasy\": (\"فانتازيا\", \"fantasy\"),\n",
                "    \"History\": (\"تاريخي\", \"history\"),\n",
                "    \"Horror\": (\"رعب\", \"horror\"),\n",
                "    \"Music\": (\"موسيقى\", \"music\"),\n",
                "    \"Mystery\": (\"غموض\", \"mystery\"),\n",
                "    \"Romance\": (\"رومانسي\", \"romance\"),\n",
                "    \"Science Fiction\": (\"خيال علمي\", \"sci-fi\"),\n",
                "    \"Thriller\": (\"إثارة\", \"thriller\"),\n",
                "    \"War\": (\"حرب\", \"war\"),\n",
                "    \"Western\": (\"غرب أمريكي\", \"western\")\n",
                "}\n",
                "_WP_CATS_CACHE = {}\n",
                "\n",
                "def get_or_create_category(genre_name, wp_site_url=WP_SITE_URL, auth=None):\n",
                "    global _WP_CATS_CACHE\n",
                "    clean = genre_name.strip()\n",
                "    if not clean: return None\n",
                "    if clean in GENRE_MAP:\n",
                "        ar_name, en_slug = GENRE_MAP[clean]\n",
                "    else:\n",
                "        ar_name = clean\n",
                "        en_slug = re.sub(r'[^a-zA-Z0-9]+', '-', clean.lower()).strip('-')\n",
                "    if wp_site_url not in _WP_CATS_CACHE:\n",
                "        try:\n",
                "            res = requests.get(f\"{wp_site_url}/wp-json/wp/v2/categories?per_page=100\", headers=HEADERS, auth=auth, timeout=20)\n",
                "            _WP_CATS_CACHE[wp_site_url] = res.json() if res.status_code == 200 and isinstance(res.json(), list) else []\n",
                "        except Exception: _WP_CATS_CACHE[wp_site_url] = []\n",
                "    existing = _WP_CATS_CACHE[wp_site_url]\n",
                "    for c in existing:\n",
                "        if c.get(\"name\", \"\").strip().lower() == ar_name.lower() or c.get(\"slug\", \"\").strip().lower() == en_slug.lower():\n",
                "            return c[\"id\"]\n",
                "    # Auto-create missing category\n",
                "    try:\n",
                "        p = {\"name\": ar_name, \"slug\": en_slug, \"description\": f\"أفلام تصنيف {ar_name}\"}\n",
                "        r = requests.post(f\"{wp_site_url}/wp-json/wp/v2/categories\", json=p, headers=HEADERS, auth=auth, timeout=20)\n",
                "        if r.status_code in (200, 201):\n",
                "            cat_obj = r.json()\n",
                "            existing.append(cat_obj)\n",
                "            print(f\"[WP] ➕ Auto-created category: '{ar_name}' (ID: {cat_obj.get('id')})\")\n",
                "            return cat_obj.get(\"id\")\n",
                "        elif r.status_code == 400 and \"term_exists\" in r.text:\n",
                "            return r.json().get(\"data\", {}).get(\"term_id\")\n",
                "    except Exception as e:\n",
                "        print(f\"[WP] Notice auto-creating category '{ar_name}': {e}\")\n",
                "    return None\n",
                "\n",
                "def resolve_movie_categories(genres_raw, wp_site_url=WP_SITE_URL, auth=None):\n",
                "    if isinstance(genres_raw, str): raw = [g.strip() for g in genres_raw.split(',') if g.strip()]\n",
                "    elif isinstance(genres_raw, list): raw = [g.get('name', g) if isinstance(g, dict) else str(g).strip() for g in genres_raw]\n",
                "    else: raw = []\n",
                "    ids = []\n",
                "    for g in raw:\n",
                "        cid = get_or_create_category(g, wp_site_url, auth)\n",
                "        if cid and cid not in ids: ids.append(cid)\n",
                "    return ids\n",
                "\n",
                "def upload_poster_to_pantheon(image_url, slug):\n",
                "    if not image_url: return None\n",
                "    print(f\"[WP] Downloading TMDB poster: {image_url[:80]}...\")\n",
                "    img_data = requests.get(image_url, headers=HEADERS, timeout=30).content\n",
                "    h = {\n",
                "        \"Content-Disposition\": f'attachment; filename=\"{slug[:25]}_{int(time.time())}.jpg\"',\n",
                "        \"Content-Type\": \"image/jpeg\",\n",
                "        \"User-Agent\": HEADERS[\"User-Agent\"]\n",
                "    }\n",
                "    auth = HTTPBasicAuth(WP_USERNAME, WP_APP_PASSWORD) if WP_APP_PASSWORD else None\n",
                "    res = requests.post(f\"{WP_SITE_URL}/wp-json/wp/v2/media\", headers=h, data=img_data, auth=auth, timeout=40)\n",
                "    if res.status_code in (200, 201):\n",
                "        mid = res.json()[\"id\"]\n",
                "        print(f\"[WP] ✅ Poster attached to Pantheon Media Library (ID: {mid})\")\n",
                "        return mid\n",
                "    print(f\"[WP] Poster upload notice ({res.status_code}): {res.text[:100]}\")\n",
                "    return None\n",
                "\n",
                "def publish_movie_to_pantheon(meta, embed_url, quality=\"1080p\"):\n",
                "    \"\"\"Publish post to Pantheon WordPress with strict double quotes on iframe for Next.js regex parser.\"\"\"\n",
                "    slug = re.sub(r'[^a-zA-Z0-9]+', '-', meta['title'].lower()).strip('-')\n",
                "    media_id = upload_poster_to_pantheon(meta.get(\"poster_url\"), slug)\n",
                "    title = f\"{meta['title']} ({meta['year']})\"\n",
                "    print(f\"[WP] Publishing '{title}' to Pantheon WordPress...\")\n",
                "\n",
                "    seo_intro_paragraph = meta.get('seo_description') or f\"مشاهدة وتحميل فيلم {meta.get('title_ar', meta['title'])} ({meta['year']}) مترجم كامل بجودة 1080p BluRay عالية أون لاين.\"\n",
                "    story_paragraph = meta.get('overview_ar') or meta.get('overview') or 'تدور أحداث الفيلم في إطار مشوق ومثير مليء بالأحداث غير المتوقعة والمغامرات الشيقة.'\n",
                "\n",
                "    # Structured 16:9 Responsive Embed HTML & Clean Arabic SEO/Story Sections\n",
                "    content = f\"\"\"<div class=\"video-container\" style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; border-radius: 12px; margin-bottom: 1.5rem;\">\n",
                "    <iframe src=\"{embed_url}\" style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border: 0;\" allowfullscreen=\"true\" scrolling=\"no\" frameborder=\"0\"></iframe>\n",
                "</div>\n",
                "<div class=\"movie-seo-intro\">\n",
                "  <p>{seo_intro_paragraph}</p>\n",
                "</div>\n",
                "<div class=\"movie-story-section\">\n",
                "  <h3 class=\"story-title\">القصة</h3>\n",
                "  <p class=\"story-text\">{story_paragraph}</p>\n",
                "</div>\"\"\"\n",
                "\n",
                "    auth = HTTPBasicAuth(WP_USERNAME, WP_APP_PASSWORD) if WP_APP_PASSWORD else None\n",
                "    category_ids = resolve_movie_categories(meta.get(\"genres\", \"\"), WP_SITE_URL, auth)\n",
                "    if category_ids:\n",
                "        print(f\"[WP] Linked category IDs: {category_ids}\")\n",
                "\n",
                "    payload = {\n",
                "        \"title\": title,\n",
                "        \"content\": content,\n",
                "        \"status\": \"publish\",\n",
                "        \"meta\": {\n",
                "            \"embed_url\": embed_url,\n",
                "            \"dood_embed\": embed_url,\n",
                "            \"video_year\": str(meta.get(\"year\", \"2026\")),\n",
                "            \"imdb_rating\": str(meta.get(\"rating\", \"8.0\")),\n",
                "            \"quality\": quality,\n",
                "            \"backdrop_url\": meta.get(\"backdrop_url\") or \"\",\n",
                "            \"genres\": meta.get(\"genres\", \"\"),\n",
                "            \"overview_ar\": meta.get(\"overview_ar\", \"\"),\n",
                "            \"cast\": \", \".join(meta.get(\"cast\", [])) if isinstance(meta.get(\"cast\"), list) else str(meta.get(\"cast\", \"\")),\n",
                "            \"title_ar\": meta.get(\"title_ar\", \"\"),\n",
                "            \"seo_description\": seo_intro_paragraph\n",
                "        }\n",
                "    }\n",
                "    if category_ids: payload[\"categories\"] = category_ids\n",
                "    if media_id: payload[\"featured_media\"] = media_id\n",
                "    res = requests.post(f\"{WP_SITE_URL}/wp-json/wp/v2/posts\", json=payload, headers=HEADERS, auth=auth, timeout=30)\n",
                "    if res.status_code in (200, 201):\n",
                "        data = res.json()\n",
                "        print(f\"🎉 SUCCESS: Movie published to Pantheon WordPress!\")\n",
                "        print(f\"Post ID:   {data.get('id')}\")\n",
                "        print(f\"Post Slug: {data.get('slug')}\")\n",
                "        print(f\"Live Post: {data.get('link')}\")\n",
                "        return data\n",
                "    raise RuntimeError(f\"WP publish failed ({res.status_code}): {res.text[:250]}\")"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# @title 🚀 8. Master Pipeline Execution\n",
                "# @markdown Specify Movie Name and Year (or IMDb ID):\n",
                "\n",
                "MOVIE_TITLE = \"The Beekeeper\" # @param {type:\"string\"}\n",
                "RELEASE_YEAR = \"2024\" # @param {type:\"string\"}\n",
                "IMDB_ID = \"\" # @param {type:\"string\"}\n",
                "PREFERRED_QUALITY = \"1080p\" # @param [\"1080p\", \"720p\", \"2160p\"]\n",
                "\n",
                "def run_pipeline(title, year=None, imdb=None, quality=\"1080p\"):\n",
                "    print(\"=\" * 75)\n",
                "    print(\"  EGYMAX CLOUD AUTOMATION PIPELINE (TMDB + YTS + ARABIC HARDSUB + PANTHEON)\")\n",
                "    print(\"=\" * 75)\n",
                "    # 1. Acquire TMDB metadata & YTS torrent\n",
                "    meta = fetch_tmdb_metadata(title.strip(), year.strip() if year else None, imdb.strip() if imdb else None)\n",
                "    target_imdb = meta.get(\"imdb_id\") or (imdb.strip() if imdb else None)\n",
                "    torrent = fetch_yts_torrent(meta[\"title\"], meta[\"year\"], target_imdb, quality)\n",
                "\n",
                "    # 2. Download movie .mp4 using Aria2c into /content/download/\n",
                "    raw_video = download_with_aria2(torrent[\"torrent_url\"] or torrent[\"magnet_uri\"])\n",
                "\n",
                "    # 3. Fetch Arabic .srt via download_subtitles_for_imdb\n",
                "    arabic_srt = download_subtitles_for_imdb(target_imdb, \"/content/download\")\n",
                "\n",
                "    # 4. Burn Arabic subtitles using burn_arabic_subtitles -> *_subbed.mp4\n",
                "    burned_video = burn_arabic_subtitles(raw_video, arabic_srt)\n",
                "\n",
                "    # Determine accurate subtitle status (prevents false positive reporting)\n",
                "    if not arabic_srt:\n",
                "        arabic_sub_status = \"None (No Arabic Subtitle Found)\"\n",
                "    elif burned_video != raw_video and os.path.exists(burned_video) and os.path.getsize(burned_video) > 0:\n",
                "        arabic_sub_status = \"Burned In\"\n",
                "    else:\n",
                "        arabic_sub_status = \"Failed (Uploaded Original Unsubbed)\"\n",
                "\n",
                "    print(f\"[PIPELINE] Subtitle status: {arabic_sub_status}\")\n",
                "\n",
                "    # Dynamically rename final video so DoodStream registers the clean movie title\n",
                "    title_en = meta.get(\"title\") or title or \"Movie\"\n",
                "    release_year = meta.get(\"year\") or \"\"\n",
                "    clean_title = re.sub(r'[^\\w\\s-]', '', title_en).strip().replace(' ', '.')\n",
                "    final_filename = f\"{clean_title}.{release_year}.1080p.Arabic.Hardsub.mp4\" if release_year else f\"{clean_title}.1080p.Arabic.Hardsub.mp4\"\n",
                "    final_filepath = os.path.join(os.path.dirname(burned_video), final_filename)\n",
                "\n",
                "    if os.path.exists(burned_video):\n",
                "        if burned_video != final_filepath:\n",
                "            if os.path.exists(final_filepath):\n",
                "                try: os.remove(final_filepath)\n",
                "                except Exception: pass\n",
                "            os.rename(burned_video, final_filepath)\n",
                "            print(f\"[PIPELINE] Renamed video to dynamic title for DoodStream: {final_filename}\")\n",
                "        burned_video = final_filepath\n",
                "\n",
                "    # 5. Upload burned *_subbed.mp4 to DoodStream\n",
                "    if not verify_video_integrity(burned_video):\n",
                "        raise RuntimeError(f\"Downloaded file is corrupted or incomplete; aborting upload. ({burned_video})\")\n",
                "    embed_url = upload_to_doodstream(burned_video)\n",
                "\n",
                "    # 6. Publish directly to Pantheon WordPress with clean DoodStream embed URL\n",
                "    post_data = publish_movie_to_pantheon(meta, embed_url, torrent[\"quality\"])\n",
                "\n",
                "    # 7. Clean up temporary files: original .mp4, .srt, and generated *_subbed.mp4\n",
                "    cleanup_list = set([raw_video, burned_video, arabic_srt])\n",
                "    for p in cleanup_list:\n",
                "        if p and os.path.exists(p):\n",
                "            try:\n",
                "                os.remove(p)\n",
                "                print(f\"[CLEANUP] Deleted temporary file: {os.path.basename(p)}\")\n",
                "            except Exception: pass\n",
                "\n",
                "    print(\"\\n\" + \"=\" * 75)\n",
                "    print(\"  PIPELINE COMPLETED SUCCESSFULLY!\")\n",
                "    print(f\"  Movie:      {meta['title']} ({meta['year']})\")\n",
                "    print(f\"  Rating:     ★ {meta['rating']}\")\n",
                "    print(f\"  Arabic Sub: {arabic_sub_status}\")\n",
                "    print(f\"  Embed URL:  {embed_url}\")\n",
                "    print(f\"  Live Post:  {post_data.get('link')}\")\n",
                "    print(f\"  Next.js:    https://egymax.vercel.app/movie/{post_data.get('slug')}\")\n",
                "    print(\"=\" * 75)\n",
                "    return post_data\n",
                "\n",
                "# Execute pipeline with configured inputs\n",
                "post_result = run_pipeline(MOVIE_TITLE, RELEASE_YEAR, IMDB_ID, PREFERRED_QUALITY)"
            ]
        }
    ]
}

notebook_path = os.path.abspath("notebooks/media_worker_pipeline.ipynb")
os.makedirs(os.path.dirname(notebook_path), exist_ok=True)
with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(notebook, f, indent=2)

print(f"Generated Production Colab Notebook at: {notebook_path}")
